'\" te
.\" Copyright 1989 AT&T
.\" Copyright (c) 1985 Regents of the University of California.All rights reserved.The Berkeley software License Agreement specifies the terms and conditions for redistribution.
.\" Copyright (c) 1999 Sun Microsystems, Inc., All Rights Reserved.
.TH atq 1 "1999 年 8 月 13 日" "SunOS 5.11" "用户命令"
.SH 名称
atq \- 显示排队以在指定时间运行的作业
.SH 用法概要
.LP
.nf
\fBatq\fR [\fB-c\fR] [\fB-n\fR] [\fIusername\fR]...
.fi

.SH 描述
.sp
.LP
\fBatq\fR 实用程序显示针对当前用户排队的 \fBat\fR 作业。\fBat\fR(1) 是允许用户以后执行命令的实用程序。如果由具有 \fBsolaris.jobs.admin\fR 授权的用户调用，则 \fBatq\fR 将显示队列中的所有作业。
.sp
.LP
如果未指定选项，则作业按照执行的时间顺序显示。
.sp
.LP
当授权的用户调用 \fBatq\fR 但未指定 \fIusername\fR 时，则会显示整个队列；当指定了 \fIusername\fR 时，则仅显示属于指定用户的那些作业。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB-c\fR\fR
.ad
.RS 6n
.rt  
按照创建顺序显示排队的作业（即发出 \fBat\fR 命令的时间）。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-n\fR\fR
.ad
.RS 6n
.rt  
仅显示队列中当前的作业总数。
.RE

.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/var/spool/cron/atjobs\fR\fR
.ad
.RS 26n
.rt  
at 作业的假脱机区域。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBat\fR(1)、\fBatrm\fR(1)、\fBauths\fR(1)、\fBcron\fR(1M)、\fBauth_attr\fR(4)、\fBattributes\fR(5)
