'\" te
.\" Copyright (c) 1992, 2012, Oracle and/or its affiliates.All rights reserved.
.TH hostname 1 "2012 年 8 月 13 日" "SunOS 5.11" "用户命令"
.SH 名称
hostname \- 设置或输出当前主机系统的名称
.SH 用法概要
.LP
.nf
\fB/usr/bin/hostname\fR [[\fB-t\fR] \fIname-of-host\fR]
.fi

.LP
.nf
\fB/usr/bin/hostname\fR [\fB-D\fR]
.fi

.SH 描述
.sp
.LP
\fBhostname\fR 命令输出当前主机的名称，正如在 \fBlogin\fR 提示符前所给出的。超级用户可通过指定一个参数来设置主机名。对主机名的更改是永久性的，除非指定了 \fB-t\fR 选项。
.sp
.LP
缺省情况下，配置为 DHCP 客户机的任何系统都使用 DHCP 返回的主机名作为其主机名。在使用 \fBhostname\fR 命令手动设置主机名后，此缺省行为将发生变化。\fB-D\fR 选项可用来将系统恢复为缺省行为，确保 DHCP 客户机主机名优先于手动定义的主机名。请注意，此缺省行为在以后的 Solaris 发行版中可能会发生改变，而且 \fB-D\fR 选项的语义也可能会相应改变以反映此类改变。
.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBuname\fR(1)、\fBnodename\fR(4)、\fBattributes\fR(5)
