'\" te
.\" Copyright © 2005, Sun Microsystems, Inc. All Rights Reserved
.TH keylogout 1 "2009 年 12 月 10 日" "SunOS 5.11" "用户命令"
.SH 名称
keylogout \- 删除随 keyserv 存储的密钥
.SH 用法概要
.LP
.nf
\fB/usr/bin/keylogout\fR [\fB-f\fR]
.fi

.SH 描述
.sp
.LP
\fBkeylogout\fR 删除由密钥服务器进程 \fBkeyserv\fR(1M) 存储的密钥。尽管对密钥的进一步访问已撤销，但是，当前会话密钥在过期或刷新之前仍有效。
.sp
.LP
删除由 \fBkeyserv\fR 存储的密钥会导致需要安全 RPC 服务的所有后台作业或已调度的 \fBat\fR(1) 作业失败。因为在计算机中仅保存了一份密钥副本，所以，最好不要在 \fB\&.logout\fR 文件中调用此命令，因为这会影响同一计算机上的其他会话。
.SH 选项
.sp
.LP
支持以下选项： 
.sp
.ne 2
.mk
.na
\fB\fB-f\fR\fR
.ad
.RS 6n
.rt  
强制 \fBkeylogout\fR 删除超级用户的密钥。缺省情况下，不允许超级用户执行 \fBkeylogout\fR，因为它会中断超级用户启动的所有 RPC 服务（如 \fBNFS\fR）。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) cw(2.75i) 
lw(2.75i) lw(2.75i) 
.
属性类型属性值
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBat\fR(1)、\fBchkey\fR(1)、\fBlogin\fR(1)、\fBkeylogin\fR(1)、\fBkeyserv\fR(1M)、\fBnewkey\fR(1M)、\fBpublickey\fR(4)、\fBattributes\fR(5)
