'\" te
.\" Copyright (c) 2009, Oracle and/or its affiliates, All Rights Reserved.
.TH krb5-config 1 "2009 年 8 月 24 日" "SunOS 5.11" "用户命令"
.SH 名称
krb5-config \- 针对已安装的 Kerberos 库进行链接
.SH 用法概要
.LP
.nf
\fBkrb5-config\fR 
     [\fB--all\fR | \fB--cflags\fR | \fB--exec-prefix\fR | \fB--help\fR | \fB--libs\fR \fIlibrary\fR | 
      \fB--prefix\fR | \fB--vendor\fR | \fB--version\fR]
.fi

.SH 描述
.sp
.LP
\fBkrb5-config\fR 标识和显示针对已安装的 Kerberos 库编译和链接程序时所需的特殊标志。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB--all\fR\fR
.ad
.RS 18n
.rt  
显示版本、供应商、前缀和 \fBexec-prefix\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--cflags\fR\fR
.ad
.RS 18n
.rt  
显示构建 Kerberos 时使用的编译器标志。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--exec-prefix\fR\fR
.ad
.RS 18n
.rt  
显示构建 Kerberos 时使用的 \fBexec-prefix\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--help\fR\fR
.ad
.RS 18n
.rt  
显示用法消息。
.sp
这是缺省值。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--libs\fR \fIlibrary\fR\fR
.ad
.RS 18n
.rt  
显示与 \fIlibrary\fR 进行链接时所需的编译器选项。
.sp
支持以下 \fIlibrary\fR 值：
.sp
.ne 2
.mk
.na
\fB\fBkrb5\fR\fR
.ad
.RS 8n
.rt  
Kerberos 5 应用程序
.RE

.RE

.sp
.ne 2
.mk
.na
\fB\fB--prefix\fR\fR
.ad
.RS 18n
.rt  
显示构建 Kerberos 时使用的前缀。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--vendor\fR\fR
.ad
.RS 18n
.rt  
显示已安装的 Kerberos 实现的供应商。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--version\fR\fR
.ad
.RS 18n
.rt  
显示已安装的 Kerberos 实现的版本。
.RE

.SH 示例
.LP
\fB示例 1 \fR使用 \fB--cflags\fR 选项
.sp
.LP
以下示例显示了使用 \fBlibkrb5\fR(3LIB) 时所需的 C 编译器标志：

.sp
.in +2
.nf
% krb5-config --cflags
-I/usr/include/kerberosv5
.fi
.in -2
.sp

.LP
\fB示例 2 \fR使用 \fB--libs\fR 选项
.sp
.LP
以下示例显示了针对 \fBlibkrb5\fR(3LIB) 进行链接时所需的 C 编译器选项：

.sp
.in +2
.nf
% krb5-config --libs
-L/usr/lib -R/usr/lib -lkrb5
.fi
.in -2
.sp

.SH 退出状态
.sp
.LP
将返回以下退出值：
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 6n
.rt  
成功完成。
.RE

.sp
.ne 2
.mk
.na
\fB>\fB0\fR\fR
.ad
.RS 6n
.rt  
出现错误。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性service/security/kerberos-5
_
接口稳定性Volatile（可变）
.TE

.SH 另请参见
.sp
.LP
\fBlibgss\fR(3LIB)、\fBlibkrb5\fR(3LIB)、\fBattributes\fR(5)
