'\" te
.\" Copyright (c) 1992, Sun Microsystems, Inc.
.TH soelim 1 "1992 年 9 月 14 日" "SunOS 5.11" "用户命令"
.SH 名称
soelim \- 从 nroff 或 troff 输入中解析和消除 .so 请求
.SH 用法概要
.LP
.nf
\fBsoelim\fR [\fIfilename\fR]...
.fi

.SH 描述
.sp
.LP
\fBsoelim\fR 会读取指定文件或标准输入，并执行 \fBnroff\fR(1) 指令所暗含的以下形式的文本内容：
.sp
.in +2
.nf
\fB\&.so\fR \fIsomefile\fR
.fi
.in -2
.sp

.sp
.LP
当它们出现在输出行开头时。 
.sp
.LP
这将非常有用，因为 \fBtbl\fR(1) 之类的程序通常不会执行此操作。它允许在不同文件中放置单个表作为大型文档的一部分运行。
.sp
.LP
系统会将包含 \fB-\fR 的参数视为与标准输入对应的文件名。
.sp
.LP
可使用单引号 (\fB\&'\fR) 而不是引号 (\fB\&.\fR) 来禁止包含，即
.sp
.in +2
.nf
 ' so /usr/share/lib/tmac/tmac.s
.fi
.in -2
.sp

.SH 示例
.LP
\fB示例 1 \fR使用 \fBsoelim\fR 命令
.sp
.LP
以下是 \fBsoelim\fR 命令的示例：

.sp
.in +2
.nf
\fBexample% soelim exum?.n | tbl | nroff\fR \fB-ms\fR \fB| col | lpr\fR
.fi
.in -2
.sp

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性text/doctools
.TE

.SH 另请参见
.sp
.LP
\fBmore\fR(1)、\fBnroff\fR(1)、\fBtbl\fR(1)、\fBattributes\fR(5)
