'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1988 Sun Microsystems, Inc. - All Rights Reserved.Copyright (c) 1995 Sun Microsystems, Inc. All Rights Reserved.
.TH ypwhich 1 "1995 年 4 月 7 日" "SunOS 5.11" "用户命令"
.SH 名称
ypwhich \- 返回 NIS 服务器或映射主服务器的名称
.SH 用法概要
.LP
.nf
\fBypwhich\fR [\fB-d\fR \fIdomain\fR] [ [\fB-t\fR] \fB-m\fR [\fImname\fR] | [\fB-Vn\fR] \fIhostname\fR]
.fi

.LP
.nf
\fBypwhich\fR \fB-x\fR
.fi

.SH 描述
.sp
.LP
\fBypwhich\fR 可以返回为 NIS 客户端提供 NIS 名称服务的 NIS 服务器的名称或者映射的主服务器的名称。如果调用时未指定任何参数，将返回本地计算机的 NIS 服务器。如果指定了 \fBhostname\fR，将查询该计算机以查明正在使用的 NIS 主服务器。
.sp
.LP
有关 NIS 名称服务的概述，请参见 \fBypfiles\fR(4)。
.SH 选项
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fI domain\fR\fR
.ad
.RS 13n
.rt  
使用 \fIdomain\fR 而非缺省域。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fR
.ad
.RS 13n
.rt  
该选项可以禁止映射昵称转换。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-m\fR\fI mname\fR\fR
.ad
.RS 13n
.rt  
查找映射的 NIS 主服务器。无法使用 \fB-m\fR 指定任何 \fBhostname\fR。\fImname\fR 可以是映射名称，也可以是映射昵称。如果省略了 \fImname\fR，将生成现有映射的列表。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-x\fR\fR
.ad
.RS 13n
.rt  
显示映射昵称转换表。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-Vn\fR\fR
.ad
.RS 13n
.rt  
缺省值为 \fBypbind\fR 版本 V3。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/network/nis
.TE

.SH 另请参见
.sp
.LP
\fBypfiles\fR(4)、\fBattributes\fR(5)
