FROM local/pvgdpr-3
MAINTAINER Leo Martins lmartins@pontusnetworks.com
ARG home=/root
ENV container docker

ENV TERM=xterm-color

EXPOSE 8443 5005-5010
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]

