'\" te
.TH sane-pnm 5 "22 April 2001" "sane-backends 1.0.19" "SANE Scanner Access Now Easy"
.IX sane-pnm
.SH NAME
sane-pnm \- SANE PNM image reader pseudo-backend
.SH DESCRIPTION
The
.B sane-pnm
library implements a SANE (Scanner Access Now Easy) backend that
provides access to PNM (Portable aNyMap files, which covers PBM bitmap
files, PGM grayscale files, and PPM pixmap files).  The purpose of
this backend is primarly to aid in debugging of SANE frontends.  It
also serves as an illustrative example of a minimal SANE backend.
.SH "DEVICE NAMES"
This backend provides two devices called
.B 0
and
.BR 1.
.SH CONFIGURATION
No configuration required.
.SH FILES
.TP
.I /usr/lib/sane/libsane-pnm.a
The static library implementing this backend.
.TP
.I /usr/lib/sane/libsane-pnm.so
The shared library implementing this backend (present on systems that
support dynamic loading).
.SH ENVIRONMENT
.TP
.B SANE_DEBUG_PNM
If the library was compiled with debug support enabled, this
environment variable controls the debug level for this backend.  E.g.,
a value of 128 requests all debug output to be printed.  Smaller
levels reduce verbosity.
.SH BUGS
If the pnm backend is installed and saned is used to allow users on remote
computers to scan on the local machine, pnm files can be read by the remote
user. This is limited to the files saned can access (usually it's running as
user "sane"). All pnm files can be read if saned runs as root which isn't
recommended anyway. The pnm backend is disabled by default. If you want to use
it, enable it with configure (see configure --help for details). Be sure that
only trusted users can access the pnm backend over saned.
.SH AUTHOR
Andreas Beck, Gordon Matzigkeit, and David Mosberger

.\" Oracle has added the ARC stability level to this manual page
.SH ATTRIBUTES
See
.BR attributes (5)
for descriptions of the following attributes:
.sp
.TS
box;
cbp-1 | cbp-1
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE 
=
Availability	image/scanner/xsane/sane-backends
=
Stability	Uncommitted
.TE 
.PP
.SH SEE ALSO
sane(7)


.SH NOTES

.\" Oracle has added source availability information to this manual page
This software was built from source available at https://java.net/projects/solaris-userland.  The original community source was downloaded from  ftp://ftp2.sane-project.org/pub/sane/old-versions/sane-backends-1.0.19/sane-backends-1.0.19.tar.gz

Further information about this software can be found on the open source community website at http://www.sane-project.org/.
