'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1992, Sun Microsystems, Inc. All Rights Reserved
.TH cktime 1 "1992 年 9 月 14 日" "SunOS 5.11" "用户命令"
.SH 名称
cktime, errtime, helptime, valtime \- 显示提示；验证并返回一天中的时间
.SH 用法概要
.LP
.nf
\fBcktime\fR [\fB-Q\fR] [\fB-W\fR \fIwidth\fR] [\fB-f\fR \fIformat\fR] [\fB-d\fR \fIdefault\fR] [\fB-h\fR \fIhelp\fR] 
     [\fB-e\fR \fIerror\fR] [\fB-p\fR \fIprompt\fR] [\fB-k\fR \fIpid\fR [\fB-s\fR \fIsignal\fR]]
.fi

.LP
.nf
\fB/usr/sadm/bin/errtime\fR [\fB-W\fR \fIwidth\fR] [\fB-e\fR \fIerror\fR] [\fB-f\fR \fIformat\fR]
.fi

.LP
.nf
\fB/usr/sadm/bin/helptime\fR [\fB-W\fR \fIwidth\fR] [\fB-h\fR \fIhelp\fR] [\fB-f\fR \fIformat\fR]
.fi

.LP
.nf
\fB/usr/sadm/bin/valtime\fR [\fB-f\fR \fIformat\fR] \fIinput\fR
.fi

.SH 描述
.sp
.LP
\fBcktime\fR 实用程序可提示用户并验证回复。其作用之一是定义回复应该为时间的提示消息、帮助和错误消息的文本以及缺省值（用户按 RETURN 键时返回）。用户回复必须符合定义的一天中的时间格式。
.sp
.LP
所有消息的长度均不得超过 70 个字符，消息格式将自动设置。定义中使用的任何空格（包括\fB换行符\fR）都将除去。使用 \fB-W\fR 选项可以取消自动格式设置。如果在消息定义开头或结尾输入波浪号，将在该位置插入缺省文本，这样便可同时显示定制文本和缺省文本。
.sp
.LP
如果未定义提示、帮助或错误消息，将显示缺省消息（如\fB\fR“附注”部分所定义）。
.sp
.LP
有三个可视化工具模块与 \fBcktime\fR 命令关联。分别是 \fBerrtime\fR（用于错误消息的格式设置和显示）、\fBhelptime\fR（用于帮助消息的格式设置和显示）和 \fBvaltime\fR（用于验证回复）。这些模块应该与 \fBFML\fR 对象一起使用。在这种情况下，\fBFML\fR 对象将定义提示。如果在 \fBerrtime\fR 和 \fBhelptime\fR 模块中定义了 \fBformat\fR，则消息将说明应当采用的格式。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fI default\fR\fR
.ad
.RS 14n
.rt  
将缺省值定义为 \fIdefault\fR。缺省值不进行验证，因此无需符合任何条件。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-e\fR \fIerror\fR\fR
.ad
.RS 14n
.rt  
将错误消息定义为 \fIerror\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR \fIformat\fR\fR
.ad
.RS 14n
.rt  
指定验证输入所依据的格式。可能的格式及其定义如下： 
.sp
.in +2
.nf
\fB%H\fR  =  hour (00 - 23)
\fB%I\fR  =  hour (00 - 12)
\fB%M\fR  =  minute (00 - 59)
\fB%p\fR  =  ante meridian or post meridian
\fB%r\fR  =  time as \fB%I:%M:%S %p\fR
\fB%R\fR  =  time as \fB%H:%M\fR (the default format)
\fB%S\fR  =  seconds (00 - 59)
\fB%T\fR  =  time as \fB%H:%M:%S\fR
.fi
.in -2
.sp

.RE

.sp
.ne 2
.mk
.na
\fB\fB-h\fR \fIhelp\fR\fR
.ad
.RS 14n
.rt  
将帮助消息定义为 \fIhelp\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR\fI pid\fR\fR
.ad
.RS 14n
.rt  
指定如果用户选择异常中止，将向进程 \fBID\fR \fIpid\fR 发送信号。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR\fI prompt\fR\fR
.ad
.RS 14n
.rt  
将提示消息定义为 \fIprompt\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-Q\fR\fR
.ad
.RS 14n
.rt  
指定不允许退出作为有效的响应。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR \fIsignal\fR\fR
.ad
.RS 14n
.rt  
指定如果选择退出，将向使用 \fB-k\fR 选项定义的进程 \fBID\fR \fIpid\fR 发送信号 \fIsignal\fR。如果未指定信号，将使用 \fBSIGTERM\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-W\fR\fI width\fR\fR
.ad
.RS 14n
.rt  
指定提示、帮助和错误消息的格式设置：行长度为 \fIwidth\fR。
.RE

.SH 操作数
.sp
.LP
支持下列操作数：
.sp
.ne 2
.mk
.na
\fB\fIinput\fR\fR
.ad
.RS 9n
.rt  
要根据格式条件验证的输入。
.RE

.SH 退出状态
.sp
.LP
将返回以下退出值：
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
成功执行。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
输入中出现 \fBEOF\fR、\fB-W\fR 选项中的宽度为负数或者用法错误。
.RE

.sp
.ne 2
.mk
.na
\fB\fB3\fR\fR
.ad
.RS 5n
.rt  
用户终止（退出）。
.RE

.sp
.ne 2
.mk
.na
\fB\fB4\fR\fR
.ad
.RS 5n
.rt  
格式参数乱码。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBattributes\fR(5)
.SH 附注
.sp
.LP
\fBcktime\fR 的缺省提示为：
.sp
.in +2
.nf
Enter a time of day [?,q]:
.fi
.in -2
.sp

.sp
.LP
缺省错误消息为：
.sp
.in +2
.nf
ERROR: Please enter the time of day.  Format is <format>.
.fi
.in -2
.sp

.sp
.LP
缺省帮助消息为：
.sp
.in +2
.nf
Please enter the time of day.  Format is <format>.
.fi
.in -2
.sp

.sp
.LP
如果选择了退出选项（并且经过允许），将返回 \fBq\fR 以及返回代码 \fB3\fR。\fBvaltime\fR 模块不会生成任何输出。如果成功，将返回\fB0\fR ；如果失败，将返回非零值。
