'\" te
.\"  Copyright 1989 AT&T Copyright (c) 2002, Sun Microsystems, Inc. All Rights Reserved
.TH clear 1 "2002 年 7 月 12 日" "SunOS 5.11" "用户命令"
.SH 名称
clear \- 清除终端屏幕
.SH 用法概要
.LP
.nf
\fBclear\fR [\fIterm\fR]
.fi

.SH 描述
.sp
.LP
如果可能，\fBclear\fR 实用程序会清除终端屏幕。它将在环境中查找终端类型，如果 \fIterm\fR 操作数尚未指定终端类型，则会查询 terminfo 数据库，以确定如何清除屏幕。
.SH 操作数
.sp
.ne 2
.mk
.na
\fB\fIterm\fR\fR
.ad
.RS 8n
.rt  
表示终端类型。通常，该操作数是不必要的，因为缺省值可从环境变量 \fBTERM\fR 获取。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBtput\fR(1)、\fBattributes\fR(5)
