'\" te
.\" Copyright 1987, 1989 by the Student Information Processing Board of the Massachusetts Institute of Technology.For copying and distribution information, please see the file kerberosv5/mit-sipb-copyright.h.
.\" Portions Copyright (c) 2004, Sun Microsystems, Inc. All Rights Reserved
.TH kpasswd 1 "2001 年 7 月 30 日" "SunOS 5.11" "用户命令"
.SH 名称
kpasswd \- 更改用户的 Kerberos 口令
.SH 用法概要
.LP
.nf
\fB/usr/bin/kpasswd\fR [\fIprincipal\fR]
.fi

.SH 描述
.sp
.LP
\fBkpasswd\fR 命令用于更改 Kerberos 主体的口令。\fBkpasswd\fR 会提示您输入当前 Kerberos 口令，以便从用户 Kerberos 领域的 \fBKDC\fR 获取 \fBchangepw\fR 票证。如果 \fBkpasswd\fR 成功获取了 \fBchangepw\fR 票证，将两次提示用户输入新口令，然后口令将被更改。
.sp
.LP
如果主体是由某个策略控制的，该策略指定了新口令的长度和/或字符类数量，则新口令必须符合该策略。（五种字符类为小写、大写、数字、标点符号和所有其他字符。）
.SH 操作数
.sp
.LP
支持下列操作数：
.sp
.ne 2
.mk
.na
\fB\fIprincipal\fR\fR
.ad
.RS 13n
.rt  
更改 Kerberos 主体 \fIprincipal\fR 的口令。否则，主体将从调用 \fBkpasswd\fR 命令的用户的标识派生。
.RE

.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/tmp/ovsec_adm.\fIxxxxxx\fR\fR\fR
.ad
.RS 25n
.rt  
在口令更改操作的生命周期内使用的临时凭证高速缓存。（\fIxxxxxx\fR 是一个随机字符串。）
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性service/security/kerberos-5
_
CSIEnabled（已启用）
.TE

.SH 另请参见
.sp
.LP
\fBkerberos\fR(5) 
.SH 已知问题
.sp
.LP
如果暂停 \fBkpasswd\fR，\fBchangepw\fR 票证可能不会被销毁。
