'\" te
.\"  Copyright (c) 1988 Sun Microsystems, Inc. - All Rights Reserved.
.TH look 1 "1994 年 3 月 29 日" "SunOS 5.11" "用户命令"
.SH 名称
look \- 查找系统字典中的词语或排序列表中的行
.SH 用法概要
.LP
.nf
\fB/usr/bin/look\fR [\fB-d\fR] [\fB-f\fR] [\fB-t\fR\fIc\fR] \fIstring\fR [\fIfilename\fR]
.fi

.SH 描述
.sp
.LP
\fBlook\fR 命令将查阅排序的 \fIfilename\fR 并将输出以 \fIstring\fR 开始的所有行。
.sp
.LP
如果未指定 \fIfilename\fR，则 \fBlook\fR 会使用带 \fB-df\fR 整理序列的 \fB/usr/share/lib/dict/words\fR。
.sp
.LP
\fBlook\fR 会将要搜索词语的长度限制在 256 个字符。
.SH 选项
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fR
.ad
.RS 7n
.rt  
字典顺序。仅字母、数字、\fB制表符\fR和\fB空格\fR字符会用于比较。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR\fR
.ad
.RS 7n
.rt  
文件夹大小写。比较时不区分大小写字母。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fIc\fR\fR
.ad
.RS 7n
.rt  
设置终止字符。忽略 \fIstring\fR 中 \fIc\fR 右侧的所有字符。
.RE

.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/usr/share/lib/dict/words\fR\fR
.ad
.RS 29n
.rt  
拼写列表
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/extended-system-utilities
.TE

.SH 另请参见
.sp
.LP
\fBgrep\fR(1)、\fBsort\fR(1)、\fBattributes\fR(5)
