'\" te
.\" Copyright 1989 AT&T
.\" Copyright (c) 2000, Sun Microsystems, Inc. All Rights Reserved
.TH ruptime 1 "2000 年 11 月 6 日" "SunOS 5.11" "用户命令"
.SH 名称
ruptime \- 显示本地计算机的主机状态。
.SH 用法概要
.LP
.nf
\fBruptime\fR [\fB-ar\fR] [\fB-l\fR | \fB-t\fR | \fB-u\fR]
.fi

.SH 描述
.sp
.LP
\fBruptime\fR 实用程序为本地网络上的每台计算机提供了类似 \fBuptime\fR（请参见 \fBuptime\fR(1)）的状态行；这些状态行从网络上的每台主机大约每三分钟广播一次的包所生成。
.sp
.LP
在 11 分钟内没有收到其任何状态报告的计算机将显示为关机。
.sp
.LP
通常情况下，列表根据主机名来排序，但是可通过指定以下所列选项中的一个来更改此顺序。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB- a\fR\fR
.ad
.RS 17n
.rt  
对已空闲一个小时或更长时间的那些用户也进行计数。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r\fR\fR
.ad
.RS 17n
.rt  
颠倒排序顺序。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-l\fR | \fB-t\fR | \fB-u \fR\fR
.ad
.RS 17n
.rt  
这些选项是互斥的。使用其中一个选项会覆盖之前所使用的一个或多个选项。
.sp
.ne 2
.mk
.na
\fB\fB-l\fR\fR
.ad
.RS 6n
.rt  
按平均负荷值对显示进行排序。 
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fR
.ad
.RS 6n
.rt  
按运行时间对显示进行排序。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-u\fR\fR
.ad
.RS 6n
.rt  
按照用户数量对显示进行排序。
.RE

.RE

.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB /var/spool/rwho/whod.*\fR\fR
.ad
.RS 27n
.rt  
数据文件
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性service/network/network-clients
.TE

.SH 另请参见
.sp
.LP
\fBuptime\fR(1)、\fBrwho\fR(1)、\fBin.rwhod\fR(1M)、\fBattributes\fR(5)
