'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1994 Sun Microsystems, Inc. - All Rights Reserved.
.TH suspend 1 "1994 年 4 月 15 日" "SunOS 5.11" "用户命令"
.SH 名称
suspend \- shell 内置函数，用于停止当前 shell
.SH 用法概要
.SS "sh"
.LP
.nf
\fBsuspend\fR 
.fi

.SS "csh"
.LP
.nf
\fBsuspend\fR 
.fi

.SS "ksh"
.LP
.nf
\fBsuspend\fR 
.fi

.SH 描述
.SS "sh"
.sp
.LP
停止执行当前 shell（如果是登录 shell，则不停止）。
.SS "csh"
.sp
.LP
将 shell 停在其轨道中，很像是通过 \fB^Z\fR 向其发送了停止信号。这通常用来停止由 \fBsu\fR 启动的 shell。
.SS "ksh"
.sp
.LP
停止执行当前 shell（如果是登录 shell，则不停止）。
.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBcsh\fR(1)、\fBkill\fR(1)、\fBksh\fR(1)、\fBsh\fR(1)、\fBsu\fR(1M)、\fBattributes\fR(5)
