'\" te
.\" Copyright (c) 1985 Regents of the University of California.All rights reserved.The Berkeley software License Agreement specifies the terms and conditions for redistribution. 
.\" Copyright (c) 2000, Sun Microsystems, Inc. All Rights Reserved 
.TH tcopy 1 "2000 年 3 月 10 日" "SunOS 5.11" "用户命令"
.SH 名称
tcopy \- 复制磁带
.SH 用法概要
.LP
.nf
\fBtcopy\fR \fIsource\fR [\fIdestination\fR]
.fi

.SH 描述
.sp
.LP
\fBtcopy\fR 实用程序可复制挂载到 \fBsource\fR 参数指定的磁带机上的磁带。关于磁带内容的唯一假设是，最后将有两个磁带标记。
.sp
.LP
仅当指定了源磁带机，\fBtcopy\fR 才会扫描磁带并显示关于记录和磁带文件大小的信息。如果指定了目标，则 \fBtcopy\fR 会将源磁带复制到 \fIdestination\fR 磁带，并会保留块。复制时，\fBtcopy\fR 生成的输出与扫描磁带时所生成的输出相同。
.sp
.LP
\fBtcopy\fR 实用程序需要使用与 Berkeley 兼容的设备名称。例如，
.sp
.in +2
.nf
example% \fBtcopy /dev/rmt/1b /dev/rmt/2b\fR
.fi
.in -2
.sp

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBmt\fR(1)、\fBioctl\fR(2)、\fBattributes\fR(5)
.SH 附注
.sp
.LP
\fBtcopy\fR 仅在支持相关 \fBioctl\fR(2) 请求集的系统上运行。
