'\" te
.\" Copyright (c) 2000, 2011, Oracle and/or its affiliates.All rights reserved.
.TH unix2dos 1 "2011 年 7 月 7 日" "SunOS 5.11" "用户命令"
.SH 名称
unix2dos \- 将文本文件从 ISO 格式转换为 DOS 格式
.SH 用法概要
.LP
.nf
\fBunix2dos\fR [\fB-ascii\fR] [\fB-iso\fR] [\fB-7\fR] 
     [\fB-437\fR | \fB-850\fR | \fB-860\fR | \fB-863\fR | \fB-865\fR] \fIoriginalfile\fR \fIconvertedfile\fR
.fi

.SH 描述
.sp
.LP
\fBunix2dos\fR 会将 \fBISO\fR 标准字符转换为 \fBDOS\fR 扩展字符集中的对应字符。
.sp
.LP
可以从 \fBDOS\fR 或 SunOS 调用此命令。但是，文件名必须符合调用该命令的环境的约定。
.sp
.LP
如果原始文件和转换后的文件相同，则 \fBunix2dos\fR 将在转换后重写原始文件。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB-ascii\fR\fR
.ad
.RS 10n
.rt  
添加回车，并将 SunOS 格式文本文件中的文件结尾字符转换为符合 \fBDOS\fR 要求的字符。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-iso\fR\fR
.ad
.RS 10n
.rt  
这是缺省值。将 \fBISO\fR 标准字符转换为 \fBDOS\fR 扩展字符集中对应的字符。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-7\fR\fR
.ad
.RS 10n
.rt  
将 8 位 SunOS 字符转换为 7 位 \fBDOS\fR 字符。
.RE

.sp
.LP
在非 i386 系统上，\fBunix2dos\fR 将尝试获取键盘类型以确定要使用的代码页。否则，缺省使用 US。用户可以用以下选项之一覆盖代码页：
.sp
.ne 2
.mk
.na
\fB\fB-437\fR\fR
.ad
.RS 8n
.rt  
使用 US 代码页
.RE

.sp
.ne 2
.mk
.na
\fB\fB-850\fR\fR
.ad
.RS 8n
.rt  
使用多语言代码页
.RE

.sp
.ne 2
.mk
.na
\fB\fB-860\fR\fR
.ad
.RS 8n
.rt  
使用葡萄牙语代码页
.RE

.sp
.ne 2
.mk
.na
\fB\fB-863\fR\fR
.ad
.RS 8n
.rt  
使用加拿大法语代码页
.RE

.sp
.ne 2
.mk
.na
\fB\fB-865\fR\fR
.ad
.RS 8n
.rt  
使用丹麦语代码页
.RE

.SH 操作数
.sp
.LP
需要使用以下操作数：
.sp
.ne 2
.mk
.na
\fB\fIoriginalfile\fR\fR
.ad
.RS 17n
.rt  
要转换为 \fBDOS\fR 格式的 \fBISO\fR 格式原始文件。
.RE

.sp
.ne 2
.mk
.na
\fB\fIconvertedfile\fR\fR
.ad
.RS 17n
.rt  
从原始 \fBISO\fR 文件格式转换过来的 \fBDOS\fR 格式新文件。
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBdos2unix\fR(1)、\fBls\fR(1)、\fBattributes\fR(5)
.SH 诊断
.sp
.ne 2
.mk
.na
\fB\fBFile \fIfilename\fR not found, or no read permission\fR\fR
.ad
.sp .6
.RS 4n
您指定的输入文件不存在，或者您没有读取权限。使用 SunOS 命令 \fBls\fR \fB-l\fR 进行检查（请参见 \fBls\fR(1)）。
.RE

.sp
.ne 2
.mk
.na
\fB\fBBad output filename \fIfilename\fR, or no write permission\fR\fR
.ad
.sp .6
.RS 4n
您指定的输出文件无效，或者您对该文件或者包含该文件的目录没有写入权限。另外还要检查驱动器没有写保护。
.RE

.sp
.ne 2
.mk
.na
\fB\fBError while writing to temporary file\fR\fR
.ad
.sp .6
.RS 4n
转换文件时发生了错误，可能是因为当前驱动器上的空间不够。使用 \fBDIR\fR 命令检查当前驱动器上的空间量。此外还要确定缺省驱动器是否启用了写入（没有写入保护）。发生此错误时，原始文件保持不变。
.RE

.sp
.ne 2
.mk
.na
\fB\fBTranslated tmpfile name = \fIfilename\fR.\fR\fR
.ad
.br
.na
\fB\fBCould not rename tmpfile to \fIfilename\fR.\fR\fR
.ad
.sp .6
.RS 4n
程序无法执行文件转换中的最后一步。转换后的文件存储在此消息的第二行上指示的名称下。
.RE

