'\" te
.\" Copyright (c) 1992, 2011, Oracle and/or its affiliates.All rights reserved.
.TH whatis 1 "2011 年 5 月 8 日" "SunOS 5.11" "用户命令"
.SH 名称
whatis \- 显示一行关键字摘要
.SH 用法概要
.LP
.nf
\fBwhatis\fR \fIcommand\fR...
.fi

.SH 描述
.sp
.LP
\fBwhatis\fR 可以查找指定的 \fIcommand\fR 并显示手册部分的标题行。随后可以运行 \fBman\fR(1) 命令以获取更多信息。如果行以 \fBname(\fIsection\fR)\fR. .  开头，则可以执行 \fBman\fR \fB-s\fR\fB\fIsection\fR name\fR 以获取相应文档。尝试使用 \fBwhatis ed\fR，然后应执行 \fBman\fR \fB-s\fR \fB1 ed\fR 以获取 \fBed\fR(1) 的手册页。
.sp
.LP
\fBwhatis\fR 实际上只是 \fBman\fR(1) 命令的 \fB-f\fR 选项。
.sp
.LP
\fBwhatis\fR 使用 \fB/usr/share/man/man_index/*\fR 索引文件。索引文件可以由 SMF 服务自动生成（如 \fBman\fR(1) 和 \fBman\fR(5) 中所述），也可以使用带有 \fB-w\fR 选项的 \fBcatman\fR(1M) 来手动生成。如果索引文件不存在，\fBwhatis\fR 运行速度会比较慢，因为它会直接从手册页文件中查找。 
.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/usr/share/man/man_index/*\fR\fR
.ad
.RS 30n
.rt  
目录和关键字数据库。
.sp
生成的文件包括： 
.RS +4
.TP
.ie t \(bu
.el o
\fB/usr/share/man/man_index/man.idx\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fB/usr/share/man/man_index/man.dic\fR
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fB/usr/share/man/man_index/man.frq\fR 
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fB/usr/share/man/man_index/man.pos\fR
.RE
.RE

.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性text/doctools
_
CSIEnabled（已启用）
_
接口稳定性Committed（已确定）
.TE

.SH 另请参见
.sp
.LP
\fBapropos\fR(1)、\fBman\fR(1)、\fBcatman\fR(1M)、\fBattributes\fR(5)、\fBman\fR(5)
