'\" te
.\" Copyright (c) 1992, Sun Microsystems, Inc.
.TH soelim 1 "1992 年 9 月 14 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
soelim \- nroff または troff 入力からの .so 要求の解決および削除
.SH 形式
.LP
.nf
\fBsoelim\fR [\fIfilename\fR]...
.fi

.SH 機能説明
.sp
.LP
\fBsoelim\fR は、指定されたファイルまたは標準入力を読み取り、\fBnroff\fR(1) 指令が
.sp
.in +2
.nf
\fB\&.so\fR \fIsomefile\fR
.fi
.in -2
.sp

.sp
.LP
次の形式で入力行の先頭に表示された場合、暗黙的に指定されたテキストの取り込みを実行します。 
.sp
.LP
通常、これは \fBtbl\fR(1) などのプログラムでは実行されないため、役に立ちます。これにより、別個のファイル内に配置された個別のテーブルを大きなドキュメントの一部として実行することが可能になります。
.sp
.LP
\fB-\fR からなる引数は、標準入力に対応するファイル名として取得されます。
.sp
.LP
次に示すように、ドット (\fB\&.\fR) ではなく単一引用符 (\fB\&'\fR) を使用することで、取り込みを抑制できます。
.sp
.in +2
.nf
 ' so /usr/share/lib/tmac/tmac.s
.fi
.in -2
.sp

.SH 使用例
.LP
\fB例 1 \fR\fBsoelim\fR コマンドの使用
.sp
.LP
次は、\fBsoelim\fR コマンドの例です。

.sp
.in +2
.nf
\fBexample% soelim exum?.n | tbl | nroff\fR \fB-ms\fR \fB| col | lpr\fR
.fi
.in -2
.sp

.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件text/doctools
.TE

.SH 関連項目
.sp
.LP
\fBmore\fR(1)、\fBnroff\fR(1)、\fBtbl\fR(1)、\fBattributes\fR(5)
