'\" te
.\" Copyright (c) 2005, Sun Microsystems, Inc.
.TH which 1 "2005 年 3 月 30 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
which \- コマンドの検索と、そのパス名または別名の表示
.SH 形式
.LP
.nf
\fBwhich\fR [\fIname\fR]...
.fi

.SH 機能説明
.sp
.LP
\fBwhich\fR は、名前のリストを受け取り、それらの名前がコマンドとして指定されると実行される別名またはユーティリティーを特定します。 
.sp
.LP
各 \fIname\fR オペランドは、それが別名である場合には、展開されます。それ以外の場合は、ユーザーのパス内で、\fIname\fR と一致する名前のユーティリティーが検索されます。別名は、ユーザーの \fB\&.cshrc\fR ファイルから取得されます。\fIpath\fR は、現在のシェル実行環境から取得されます。
.SH オペランド
.sp
.LP
次のオペランドを指定できます。
.sp
.ne 2
.mk
.na
\fB\fIname\fR\fR
.ad
.RS 8n
.rt  
検索するコマンドの名前。
.RE

.SH 終了ステータス
.sp
.LP
次の終了ステータスが返されます。
.sp
.ne 2
.mk
.na
\fB\fB0\fR \fR
.ad
.RS 7n
.rt  
正常終了。
.RE

.sp
.ne 2
.mk
.na
\fB\fB>0\fR \fR
.ad
.RS 7n
.rt  
1 つ以上の \fIname\fR オペランドが見つからなかったか、エラーが発生しました。
.RE

.SH ファイル
.sp
.ne 2
.mk
.na
\fB\fB~/.cshrc\fR\fR
.ad
.RS 12n
.rt  
別名およびパス値のソース
.RE

.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBcsh\fR(1)、\fBattributes\fR(5)
.SH 診断
.sp
.LP
名前が複数の単語の別名である、または引数名で実行可能ファイルがパス内に見つからなかった場合に、診断が提供されます。
.SH 注意事項
.sp
.LP
\fBwhich\fR ユーティリティーは、シェル内蔵コマンドではありません。
.SH 使用上の留意点
.sp
.LP
別名が依存する \fBprompt\fR 変数が設定されている \fB~/.cshrc\fR ファイルを補償するため、\fBwhich\fR はこの変数を \fBNULL\fR に設定します。\fB~/.cshrc\fR が出力を生成するか、\fB prompt\fR が設定されているときに入力を要求する場合、\fBwhich\fR は奇妙な結果を生成することがあります。
