'\" te
.TH gpg-error 1 "31 Jul 2008" "SunOS 5.11" "User Commands"
.SH "NAME"
gpg-error \- Get the description for specified error numbers\&.
.SH "SYNOPSIS"
.PP
\fBgpg-error\fR \fB\fIerrorno\fR\fR [\fB\fI\&.\&.\&.\fR\fR]
.SH "DESCRIPTION"
.PP
gpg-error is a tool that returns the description of specified error numbers\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIerrorno\fR\fR\fR
.in +9n
.rt
Error numbers for which you want to get the description\&.
.sp
.sp 1
.in -9n
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
\fB\fB0\fR\fR
.in +9n
.rt
Application
exited successfully
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB\fB1\fR\fR
.in +9n
.rt
Application
exited with failure
.sp
.sp 1
.in -9n
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/bin/gpg-error\fR \fR
.in +24n
.rt
Executable for gpg-error
.sp
.sp 1
.in -24n
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitylibrary/security/libgpg-error
Interface stabilityVolatile
.TE
.sp
.SH "SEE ALSO"
.PP
\fBgpg-error-config\fR(1),
\fBlibgpg-error\fR(3),
\fBattributes\fR(5)
.PP
Written by Jeff Cai, Sun Microsystems Inc\&., 2008\&.
...\" created by instant / solbook-to-man, Wed 18 Dec 2013, 18:59
...\" LSARC 2008/207 GNOME 2.22
