'\" te
.TH gtk-builder-convert 1 "21 Nov 2007" "SunOS 5.11" "User Commands"
.SH "NAME"
gtk-builder-convert \- Glade file conversion utility
.SH "SYNOPSIS"
.PP
\fBgtk-builder-convert\fR [-\fB-help\fR] [-\fB-skip-windows\fR] [-\fB-root=\fIname\fR\fR] {input_glade_file} {output_XML_file}
.SH "DESCRIPTION"
.PP
\fBgtk-builder-convert\fR converts glade files into XML files which can be
loaded with GTKBuilder\&.
.PP
It expects the first argument to be the name of the glade file and the second
argument to be the file name where the generated XML is saved\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBh\fR, -\fB-help\fR\fR
.in +24n
.rt
Display help text\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBw\fR, -\fB-skip-windows\fR\fR
.in +24n
.rt
Convert everything but GtkWindow subclasses\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBr\fR, -\fB-root\fR=\fIname\fR\fR
.in +24n
.rt
Convert only the widget named \fIname\fR and its children\&.
.sp
.sp 1
.in -24n
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIinput_glade_file\fR\fR\fR
.in +24n
.rt
Input glade file\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB\fB\fIoutput_XML_file\fR\fR\fR
.in +24n
.rt
Output XML file\&.
.sp
.sp 1
.in -24n
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
\fB\fB0\fR\fR
.in +9n
.rt
Application exited successfully
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB\fB>0\fR\fR
.in +9n
.rt
Application exited with failure
.sp
.sp 1
.in -9n
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/bin/gtk-builder-convert\fR\fR
.in +32n
.rt
The command-line executable for the application\&.
.sp
.sp 1
.in -32n
.SH "ATTRIBUTES"
.PP
See
\fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitylibrary/desktop/gtk2
Interface stabilityCommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBglade-3\fR(1),
\fBlibglade-2\&.0\fR(3),
\fBlibgtk-x11-2\&.0\fR(3),
\fBattributes\fR(5),
\fBgnome-interfaces\fR(5)
.PP
Latest version of the \fIGNOME Desktop User Guide\fR for your
platform\&.
.SH "NOTES"
.PP
Toolbars are not handled\&.
.PP
Support for accessibility is not yet implemented\&.
.PP
The script requires a python interpreter to run\&.
.PP
Written by Johan Dahlin, Async Open Source, Ghee Teo, Sun Microsystems Inc\&.,
2007\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
