'\" te
.TH ppm2tiff 1 "26 Mar 2004" "SunOS 5.11" "User Commands"
.SH "NAME"
ppm2tiff \- create
a TIFF file from a PPM image file
.SH "SYNOPSIS"
.PP
\fBppm2tiff\fR [\fB\fIoptions\fR\fR] [\fB\fIinput\&.ppm\fR\fR] \fB\fIoutput\&.tif\fR\fR
.SH "DESCRIPTION"
.PP
\fBppm2tiff\fR converts a file in the PPM image format to
TIFF\&. By default, the TIFF image is created with data samples packed (PlanarConfiguration=1),
compressed with the Lempel-Ziv and Welch algorithm (Compression=5), and with
each strip no more than 8 kilobytes\&. These characteristics can be overridden
or explicitly specified with the options described below\&.
.PP
If the PPM file contains grayscale data, the PhotometricInterpretation
tag is set to 1 (min-is-black)\&. Otherwise, the PhotometricInterpretation tag
is set to 2 (RGB)\&.
.PP
If no PPM file is specified on the command line, \fBppm2tiff\fR
reads from the standard input\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBc\fR\fR
.in +16n
.rt
Specify a compression
scheme to use when writing image data:
.sp
.sp
.ne 2
.mk
\fB-\fBc jpeg\fR\fR
.in +24n
.rt
Baseline
JPEG compression algorithm\&.
.sp
.sp 2
.in -24n
.sp
.ne 2
.mk
\fB-\fBc lzw\fR\fR
.in +24n
.rt
Lempel-Ziv
and Welch algorithm\&. This is the default algorithm\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBc none\fR\fR
.in +24n
.rt
No compression\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBc packbits\fR\fR
.in +24n
.rt
PackBits
compression algorithm\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBc zip\fR\fR
.in +24n
.rt
Deflate compression
algorithm\&.
.sp
.sp 1
.in -24n
.sp 0
.in -16n
.sp
.ne 2
.mk
\fB-\fBr\fR\fR
.in +16n
.rt
Write data with
a specified number of rows per strip\&. By default, the number of rows per strip
is selected so that each strip is approximately 8 kilobytes\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBR\fR\fR
.in +16n
.rt
Mark the resultant
image to have the specified X and Y resolution, in dots per inch\&.
.sp
.sp 1
.in -16n
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIinput\&.ppm\fR\fR\fR
.in +16n
.rt
The name of the input file that contains PPM data\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB\fB\fIoutput\&.tif\fR\fR\fR
.in +16n
.rt
The name of the output file that contains TIFF data\&.
.sp
.sp 1
.in -16n
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilityimage/library/libtiff
Interface stabilityUncommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBtiffinfo\fR(1), \fBtiffcp\fR(1), \fBtiffmedian\fR(1), \fBlibtiff\fR(3)
.SH "NOTES"
.PP
Updated by Breda McColgan, Sun Microsystems Inc\&., 2004\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
...\" LSARC 2003/085 libtiff, libjpeg, and libpng
