'\" te
.TH tiffdump 1 "26 Mar 2004" "SunOS 5.11" "User Commands"
.SH "NAME"
tiffdump \- display
verbatim information about TIFF files
.SH "SYNOPSIS"
.PP
\fBtiffdump\fR [\fB\fIoptions\fR\fR] \fB\fIinput\&.tif\fR\fR\&...
.SH "DESCRIPTION"
.PP
\fBtiffdump\fR displays directory information from files created
according to the Tag Image File Format, Revision 6\&.0\&. The header of each TIFF
file (magic number, version, and first directory offset) is displayed, followed
by the tag contents of each directory in the file\&. For each tag, the name,
datatype, count, and values are displayed\&. When the symbolic name for a tag
or datatype is known, the symbolic name is displayed followed by the numeric
decimal value\&. Tag values are displayed enclosed in "<>" characters
immediately preceded by the value of the count field\&. For example, an ImageWidth
tag might be displayed as "ImageWidth (256) SHORT (3) 1<800>"\&.
.PP
\fBtiffdump\fR is particularly useful for investigating the
contents of TIFF files that \fBlibtiff\fR does not understand\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBh\fR\fR
.in +16n
.rt
Force numeric
data to be displayed in hexadecimal rather than the default decimal
format\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBo\fR\fR
.in +16n
.rt
Dump the contents
of the IFD at a particular file offset\&. The file offset may be specified using
the usual C-style syntax, that is, a leading "0x" for hexadecimal
and a leading "0" for octal\&.
.sp
.sp 1
.in -16n
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIinput\&.tif\fR\fR\fR
.in +16n
.rt
The name of the TIFF file\&.
.sp
.sp 1
.in -16n
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilityimage/library/libtiff
Interface stabilityUncommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBtiffinfo\fR(1), \fBlibtiff\fR(3)
.SH "NOTES"
.PP
Updated by Breda McColgan, Sun Microsystems Inc\&., 2004\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
...\" LSARC 2003/085 libtiff, libjpeg, and libpng
