.TH K-tools 7
.SH NAME
K-tools \- Tools included in K
.SH DESCRIPTION
The K installation includes tools and utilities for performing common tasks.
The majority of these are text- and keyboard- based rather than the
GUI applications familiar to users of modern Linux desktop environments. For
your convenience, here's a list describing many of the installed tools:
.RS
.TS
tab(@);
lb | lb
l | l .
Tool@Description
_
abduco@terminal session manager
aspell@spell checker
bluetoothctl@Bluetooth control and configuration
cava@curses-based audio spectrum analyzer
centerim@chat client
cgdb@curses-based gdb interface
chromium-bsu@space shooter game
dict@dictionary
diction@diction checker
duplicity@manage file backups and restores
dvtm@terminal tiling window manager
gifview@GIF viewer
lftp@sophisticated file transfer program
mpv@video player
mutt@email client
ncmpcpp@music player
nmcli@network manager
nmtui@curses-based network manager interface
pamixer@curses-based Pulseaudio mixer
pinfo@info browser w/ vi-like key bindings
podbeuter@podcast download manager
powwow@MUD client
ranger@curses-based file manager
recordmydesktop@screencast recorder
scrot@screen capture
seren@VoIP/text client
simple-mtpfs@mount MTP (smart phone) file system
slrn@NNTP newsreader
st@terminal
style@style checker
surf@keyboard-driven web browser
sxiv@image viewer
tabbed@generic tabbed XEmbed container
tig@curses-based git interface
udisksctl@mount/unmount hot-plugged storage
vis@text editor
vit@task organizer
w3m@keyboard-driven textual web browser
weechat@IRC client
wn@Wordnet database
wyrd@calendar and reminders
yapet@password manager
zathura@PDF, Postscript and DjVU viewer
.TE
.RE
.PP
The following programming languages are preinstalled:
.RS
.TS
tab(@);
lb | lb
l | l .
Language@Description
_
clang@gcc compatible
clang++@g++ compatible
gcc@GNU C; see gcc(1)
g++@GNU C++; see gcc(1)
nickle@scripting language (no standard)
xs@command shell (no standard)
.TE
.RE
.PP
Additional tools may be installed via the installer's `--addon` option. These
include:
.RS
.TS
tab(@);
lb | lb
l | l .
Addon@Description
_
audio@audio production tools
axe-fx@utilities for Fractal Audio's Axe-FX II
backup@backup and restore scripts using duplicity
clips@expert system shell (no standard)
dlna@DLNA server (requires additional configuration)
gforth@GNU FORTH; complies w/ ANS FORTH
gmail@exim as a GMail client
haskell@Haskell Stack
lilypond@Lilypond music engraver (also: Music21 toolkit)
lisp@CLISP (Common Lisp; INCITS 226-1994 [R1999])
mame-games@several of my favorite arcade games
newsboat@RSS feed reader
parallax@Parallax Propeller development toolchain
ponylang@Pony language (no standard)
projectM@audio visualizer (derived from MilkDrop)
radeon@Radeon/ATI/AMD GPU/OpenCL support
rust@Rust language (no standard)
.TE
.RE
.PP
In a small number of cases, GUI-based tools are provided. These may be
keyboard-driven, although the interactions can be more cumbersome than if they
were built from the ground up for keyboard control. These tools include:
.RS
.TS
tab(@);
lb | lb
l | l .
Tool@Description
_
falkon@Blink-based web browser
libreoffice@Office-compatible suite
lucidlife@Conway's life
mandelbulber2@fractal 3D image explorer
mandelbulber@fractal 3D image explorer
modem-manager-gui@Modem Manager (WWAN) tool
nm-connection-editor@Network Manager connection editor
pulseaudio-equalizer-gtk@audio graphic equalizer
virt-manager@virtual machine manager
system-config-kickstart@kickstart file creator
.TE
.RE
