.TH K-workflow 7
.SH NAME
K-workflow \- Workflow tips for K's window manager
.SH TIPS
.IP \(bu 3
A list of window manager bindings is available via the
.B wmb
command.
.IP \(bu 3
The workspace list is circular.
.IP \(bu 3
The window list is circular.
.IP \(bu 3
Focus a window by moving the pointer over the window.
Focus is removed from a window when another is focused.
.IP \(bu 3
Windows are not automatically raised when focused.
.IP \(bu 3
Cycle through a stack of windows by successively lowering
.RI ( Mod4+r )
the top window.
.IP \(bu 3
New windows are placed, in the absence of other forces (such as
.I ~/.Xresources
or client logic), according to the position of the mouse pointer.
.IP \(bu 3
When changing focus via the keyboard, the pointer is moved to the center
of the newly focused window.
.IP \(bu 3
The pointer is hidden by typing.
.IP \(bu 3
The window manager uses the window's urgency hint to lock a window
against deletion (see the
.IR Mod4+a " binding)."
The window manager does not respond to a bell to set the urgency hint.
Urgency hints are processed normally for windows contained by
.BR tabbed (1).
.IP \(bu 3
.IR Menu " (or " Mod4+w )
pops up a list of programs on
.B $PATH
or defined as
.BR xs (1)
functions.
This may be used to launch programs that have a GUI or to run scripts or
.BR xs (1)
functions that spawn a terminal.
.IP \(bu 3
The behavior of the window manager's resize commands may be altered by
the client, e.g. to respect character-cell boundaries in a terminal.
.IP \(bu 3
.I Mod4+semicolon
pops up a list of windows. Each row displays a window index, visibility flag,
window ID, workspace number
.RB ( *
for windows that are present on all workspaces), screen region, hostname
and window title.
The visibility flag is
.B =
for a window which is visible on a workspace and
.B \-
for a window which is hidden.
(Windows on other workspaces are flagged as
.B ?\,
because the window manager does not report minimization.)
Select the desired window to switch to its workspace and raise and focus
the window.
.RS
.PP
Note that the window index and workspace number are prefixed in the menu.
This is to support filtering by multiple selection. For example, to select
from among the windows on a particular workspace, first type the workspace
ID (with its prefix). This will reduce the set of selections to just the
windows on that workspace. Type a space to begin the next search term, or
use the arrow keys to choose the window of interest.
.PP
A window's presence upon a screen region is detected and labeled in this order:
.RS
.TS
tab(@);
lb l .
FS@window exactly matches display
TL@window covers top-left point
BL@window covers bottom-left point
TR@window covers top-right point
BR@window covers bottom-right point
OC@window covers center point
TC@window covers top-center point
BC@window covers bottom-center point
\-\|\-@none of the above
.TE
.RE
.RE
.IP \(bu 3
Hide the focused window using
.IR Mod4+i .
It's helpful to title a window with a useful mnemonic before hiding.
Use the window list
.RI ( Mod4+semicolon )
to unhide a window, or
.I Shift+Mod4+i
to unhide all windows.
.IP \(bu 3
Some characters not on the keyboard may be entered using a compose sequence.
The
.B cs
command lists the available composed characters. The compose key (labelled
.I <Multi_key>
in the
.B cs
listing) is bound to
.IR PrintScreen .
To enter a composed character, press and release keys in the order shown
in
.BR cs ;
the
.I <Multi_key>
is not a modifier key.
.IP \(bu 3
Notifications pop up at the top of the screen in response to commands;
these are white text on a black background.
Asynchronous notifications pop up one-third of the way down the screen;
these have a colored background.
All notifications time out.
To dismiss a notification before it times out, right-click anywhere
in the notification bar.
.IP \(bu 3
The
.BR xs (1)
shell prompt displays an indicator when the prior command has
finished with a nonzero exit code or has finished its output without a
terminating newline.
.IP \(bu 3
.BR readline (3)
is configured to use
.BR vi -like
bindings.
Use the
.B rlb
command to list these bindings.
.IP \(bu 3
The
.BR virt-viewer (1)
command opens a window onto a VM's console.
Toggle pointer capture using
.I Control_L+Alt_L
when the viewer is focused.
Copy/paste between guest and host is supported for both the primary and
clipboard selections when the guest runs
.BR spice-vdagent (1),
which is done by
.I ~/.xinitrc
when
.BR K (1)
is installed on the guest.
.IP \(bu 3
.I Mod4+slash
pops up a list of defined virts, excluding those with names ending in
.IR -base .
Selecting from this list starts the virt if needed and
displays the virt's console using
.BR virt-viewer (1).
A virt continues to run if its viewer is killed.
.IP \(bu 3
An interactive guest's X display resolution may be changed using the
.BI resize " xres yres"
command from an
.BR xs (1)
shell in the guest (assuming that
.BR K (1)
is installed on the guest).
.IP \(bu 3
The window manager is restarted via the system's
.I Ctrl+Alt+BackSpace
chord; this also terminates processes owned by the session.
Restart is followed immediately by an automatic login.
.IP \(bu 3
The proper way to switch displays is to change connections as desired,
then restart the window manager.
.RS
.PP
Pay attention to connections so you don't try to restart the window
manager through a keyboard that got disconnected with its display.
Conversely, the keyboard associated with a docked display may not be
active until the OS has attached the docked hardware, which may require
restarting the window manager.
.PP
Note that the window manager does not process keyboard requests when
the screen is locked.
The system's
.I Ctrl+Alt+BackSpace
chord is always recognized.
.RE
.IP \(bu 3
An
.I .xspath
file may contain commands to extend
.B $PATH
upon entry to the directory containing the
.I .xspath
file.
See
.I ~/.xsin
for additional details.
