'\" te
.TH libgio-2\&.0 3 "14 May 2008" "SunOS 5.11" "C Library Functions"
.SH "NAME"
libgio-2\&.0 \- GLib Object System
.SH "DESCRIPTION"
.PP
GIO provides a modern, easy-to-use virtual file system (VFS) API\&.  GIO provides
facilities for file monitoring, asynchronous I/O and filename completion\&.  GIO
provides implementation for local use\&.  Implementions for various network file
systems are provided by gvfs as loadable modules\&.
.PP
To access the API documentation, you must install the developer version of the
package\&.
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/lib/libgio-2\&.0\&.so\fR\fR
.in +32n
.rt
GLib I/O shared library
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB\fB/usr/share/gtk-doc/html/gio\fR\fR
.in +32n
.rt
Location of developer documentation
.sp
.sp 1
.in -32n
.SH "ATTRIBUTES"
.PP
See
\fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitylibrary/glib2
Interface stabilityVolatile
.TE
.sp
.SH "SEE ALSO"
.PP
\fBglib-genmarshal\fR(1),
\fBglib-gettextize\fR(1),
\fBglib-mkenums\fR(1),
\fBgobject-query\fR(1)
\fBlibglib-2\&.0\fR(3),
\fBlibgobject-2\&.0\fR(3),
\fBlibgiomm-2\&.4\fR(3),
\fBattributes\fR(5),
\fBgnome-interfaces\fR(5)
.SH "NOTES"
.PP
Written by Brian Cameron, Sun Microsystems Inc\&., 2008\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
