'\" te
.TH libpango-1\&.0 3 "31 Aug 2004" "SunOS 5.11" "C Library Functions"
.SH "NAME"
libpango-1\&.0, libpangoft2-1\&.0, libpangox-1\&.0, libpangoxft-1\&.0, libpangocairo-1\&.0 \- layout and rendering of internationalized text with X11, FreeType2,
Xft, and Cairo support
.SH "DESCRIPTION"
.PP
Pango provides a framework for the layout and rendering of internationalized
text\&. The name is derived from the Greek "Pan" which means "All", and the
Japanese "Go" which means "Language"\&.
.PP
To access the API documentation, you must install the developer version of the
package\&.
.SH "FILES"
.PP
The following files are used by this library:
.sp
.ne 2
.mk
\fB\fB/usr/lib/libpango-1\&.0\&.so\fR\fR
.in +32n
.rt
Internationalization shared library
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB/usr/lib/libpangocairo-1\&.0\&.so\fR
.in +32n
.rt
Pango Cairo rendering backend shared library
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB/usr/lib/libpangox-1\&.0\&.so\fR
.in +32n
.rt
X11 support for Pango shared library
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB/usr/lib/libpangoft2-1\&.0\&.so\fR
.in +32n
.rt
FreeType2 font and rendering backend for Pango shared library
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB/usr/lib/libpangoxft2-1\&.0\&.so\fR
.in +32n
.rt
Font handling and rendering with the Xft backend for Pango shared library
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB\fB/usr/share/gtk-doc/html/pango\fR\fR
.in +32n
.rt
Location of developer documentation
.sp
.sp 1
.in -32n
.SH "ATTRIBUTES"
.PP
See
\fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitylibrary/desktop/pango
Interface stabilityCommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBpango-querymodules\fR(1),
\fBattributes\fR(5),
\fBgnome-interfaces\fR(5)
.SH "NOTES"
.PP
Written by Brian Cameron, Sun Microsystems Inc\&., 2003, 2004\&.
...\" created by instant / solbook-to-man, Thu 19 Jul 2012, 22:33
...\" LSARC 2001/384 Gtk+ 2.0 / glib 2.0
...\" LSARC 2001/781 location of GTK/Glib
...\" PSARC 2001/804 GTK/Glib becomes Contracted External
