.TH "Sound_Version" 3 "Thu Jan 23 2014" "Version 1.0.1" "SDL_sound" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sound_Version \- 
.PP
Information the version of SDL_sound in use\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_sound\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmajor\fP"
.br
.ti -1c
.RI "int \fBminor\fP"
.br
.ti -1c
.RI "int \fBpatch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information the version of SDL_sound in use\&. 

Represents the library's version as three levels: major revision (increments with massive changes, additions, and enhancements), minor revision (increments with backwards-compatible changes to the major revision), and patchlevel (increments with fixes to the minor revision)\&.
.PP
\fBSee Also:\fP
.RS 4
\fBSOUND_VERSION\fP 
.PP
\fBSound_GetLinkedVersion\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "int Sound_Version::major"
major revision 
.SS "int Sound_Version::minor"
minor revision 
.SS "int Sound_Version::patch"
patchlevel 

.SH "Author"
.PP 
Generated automatically by Doxygen for SDL_sound from the source code\&.
