.TH "Sound_Sample" 3 "Thu Jan 23 2014" "Version 1.0.1" "SDL_sound" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sound_Sample \- 
.PP
Represents sound data in the process of being decoded\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_sound\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBopaque\fP"
.br
.ti -1c
.RI "const \fBSound_DecoderInfo\fP * \fBdecoder\fP"
.br
.ti -1c
.RI "\fBSound_AudioInfo\fP \fBdesired\fP"
.br
.ti -1c
.RI "\fBSound_AudioInfo\fP \fBactual\fP"
.br
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.ti -1c
.RI "Uint32 \fBbuffer_size\fP"
.br
.ti -1c
.RI "\fBSound_SampleFlags\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents sound data in the process of being decoded\&. 

The \fBSound_Sample\fP structure is the heart of SDL_sound\&. This holds information about a source of sound data as it is being decoded\&. EVERY FIELD IN THIS IS READ-ONLY\&. Please use the API functions to change them\&. 
.SH "Field Documentation"
.PP 
.SS "\fBSound_AudioInfo\fP Sound_Sample::actual"
Actual audio format of sample\&. 
.SS "void* Sound_Sample::buffer"
Decoded sound data lands in here\&. 
.SS "Uint32 Sound_Sample::buffer_size"
Current size of (buffer), in bytes (Uint8)\&. 
.SS "const \fBSound_DecoderInfo\fP* Sound_Sample::decoder"
Decoder used for this sample\&. 
.SS "\fBSound_AudioInfo\fP Sound_Sample::desired"
Desired audio format for conversion\&. 
.SS "\fBSound_SampleFlags\fP Sound_Sample::flags"
Flags relating to this sample\&. 
.SS "void* Sound_Sample::opaque"
Internal use only\&. Don't touch\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SDL_sound from the source code\&.
