'\" te
.\" Copyright (c) 2007, 2013, Oracle and/or its affiliates.All rights reserved.
.TH trusted_extensions 5 "2007 年 11 月 12 日" "SunOS 5.11" "標準、環境、マクロ"
.SH 名前
trusted_extensions \- Solaris Trusted Extensions 
.SH 機能説明
.sp
.LP
Oracle Solaris の Trusted Extensions 機能には、デスクトップシステム、ウィンドウシステム、ゾーンシステム、ファイルシステム、およびネットワーク通信用に、ローカルオブジェクトとローカルプロセスのラベルが提供されています。これらのラベルは、ラベルの関係に基づいて情報のフローを制限するマルチレベルセキュリティー (MLS) ポリシーの実装に使用されます。所有権に基づく随意アクセス制御 (Discretionary Access Control、DAC) とは異なり、Trusted Extensions によって適用される MLS ポリシーは必須アクセス制御 (Mandatory Access Control、MAC) の一例です。
.sp
.LP
デフォルトでは、Trusted Extensions ソフトウェアは無効になっています。これは \fBlabeladm\fR(1M) コマンドによって有効化および無効化され (ただし完全には構成されない)、FMRI パターンによって識別される、\fBlabeld\fR(1M) サービスと関連付けられます。
.sp
.in +2
.nf
svc:/system/labeld:*
.fi
.in -2
.sp

.sp
.LP
Trusted Extensions ソフトウェアを使用する前に必要な構成については、下記の管理者ガイドを参照してください。
.SH 関連項目
.sp
.LP
\fBlabeld\fR(1M), \fBlabel_encodings\fR(4), \fBlabels\fR(5)
.sp
.LP
\fI『Trusted Extensions Configuration and Administration』\fR
.sp
.LP
\fI『Trusted Extensions User\&'s Guide』\fR
