'\" te
.TH libgailutil 3 "31 Aug 2004" "SunOS 5.11" "C Library Functions"
.SH "NAME"
libgailutil \- GTK+ Accessibility Implementation Library Utilities
.SH "DESCRIPTION"
.PP
The \fBlibgailutil\fR library provides useful accessibility
functions that are common to many GTK+ components\&.  These functions are used
when implementing accessibility support for a customized GTK+ based component\&.
.PP
To access the API documentation, you must install the developer version
of the package\&.
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/lib/libgailutil\&.so\fR \fR
.sp .6
.in +4
GTK+ Accessibility shared library
.sp
.sp 1
.in -4
.sp
.ne 2
.mk
\fB\fB/usr/share/gtk-doc/html/gail-libgail-util\fR \fR
.sp .6
.in +4
Location of developer documentation
.sp
.sp 1
.in -4
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitylibrary/desktop/gtk2
Interface stabilityVolatile
.TE
.sp
.SH "SEE ALSO"
.PP
\fBlibatk-1\&.0\fR(3),
\fBlibgtk-x11-2\&.0\fR(3),
\fBattributes\fR(5),
\fBgnome-interfaces\fR(5)
.SH "NOTES"
.PP
Written by Brian Cameron, Sun Microsystems Inc\&., 2003, 2004, 2006\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
...\" LSARC 2001/650 GNOME Accessibility
