.\" arcs_message man page
.TH man 1 "23 August 2010" "0.1" "arcs_message man page"
.SH NAME
arcs_message - get an arcs commit message using vi-
.SH SYNOPSIS
.PP
.B arcs -m "$(arcs_message)"
.PP
.B arcs -m "$(arcs_message)"
.B arcs -t "$(arcs_message)"
.SH DESCRIPTION
.B arcs_message
get an arcs commit message using vi-
.SH AUTHORS
.nf
Sam Watkins (swatkins@fastmail.fm)
.fi
.SH "SEE ALSO"
.BR arcs
.BR vi-
