.\" conflicted man page
.TH man 1 "18 April 2009" "0.1" "conflicted man page"
.SH NAME
conflicted - list files having conflicts in them
.SH SYNOPSIS
.B conflicted [dir ...]
.SH DESCRIPTION
.B conflicted
lists files having conflicts in them. It scans the content of the files for conflict markup, it does not query a version control system. It works with the markup used by
.B git
which I think is the same as that used by other version control systems. You can use
.B pacify
to resolve the conflict.
.P
.SH AUTHORS
.nf
Sam Watkins (swatkins@fastmail.fm)
.fi
.SH "SEE ALSO"
.BR pacify
.BR arcs
.BR git
