.\" git_commit_all man page
.TH man 1 "18 April 2009" "0.1" "git_commit_all man page"
.SH NAME
git_commit_all - run git-update-index on all files then git-commit -m .
.SH SYNOPSIS
.B git_commit_all
.SH DESCRIPTION
.B git_commit_all
commits all files, by running git-update-index on all files then git-commit -m .
.PP
It is useful to fix things up if
.B arcs
thinks it has committed something but actually it didn't.
.SH AUTHORS
.nf
Sam Watkins (swatkins@fastmail.fm)
.fi
.SH "SEE ALSO"
.BR arcs
.BR git
