'\" te
.TH dbus-uuidgen 1 "25 Feb 2009" "SunOS 5.11" "User Commands"
.SH "NAME"
dbus-uuidgen \- Utility to generate UUIDs
.SH "SYNOPSIS"
.PP
\fBdbus-uuidgen\fR [-\fB-ensure=\fIfile\fR\fR] [-\fB-get=\fIfile\fR\fR] [-\fB-version\fR]
.SH "DESCRIPTION"
.PP
The \fBdbus-uuidgen\fR command generates or reads a universally unique
ID\&.
.PP
Note that the D\-Bus UUID has no relationship to RFC 4122 and does not generate
UUIDs compatible with that spec\&.  Many systems have a separate command for that
(often called "uuidgen")\&.
.PP
The primary usage of \fBdbus-uuidgen\fR is to run in the post-install
script of a D\-Bus package as shown in the example section of this document\&.
.PP
This will ensure that \fB/var/lib/dbus/machine-id\fR exists and
has the uuid in it\&.  It will not overwrite an existing uuid, since this id
should remain fixed for a single machine until the next reboot at least\&.
.PP
The important properties of the machine UUID are that 1) it remains unchanged
until the next reboot and 2) it is different for any two running instances of
the OS kernel\&.  That is, if two processes see the same UUID, they should also
see the same shared memory, UNIX domain sockets, local X displays,
localhost\&.localdomain resolution, process IDs, and so forth\&.
.PP
If you run \fBdbus-uuidgen\fR with no options it just prints a new uuid
made up out of thin air\&.
.PP
If you run \fBdbus-uuidgen\fR with -\fB-get\fR, it prints the
machine UUID by default, or the UUID in the specified file if you specify a
file\&.
.PP
If you try to change an existing machine-id on a running system, it will
probably result in bad things happening\&.  Do not try to change this file\&.
Also, do not make it the same on two different systems; it needs to be
different anytime there are two different kernels running\&.
.PP
The UUID should be different on two different virtual machines, because there
are two different kernels\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fB-ensure=\fIfile\fR\fR\fR
.sp .6
.in +4
If a \fIfile\fR is not given, defaults to
\fB/var/lib/dbus/machine-id\fR\&.  If this
\fIfile\fR exists then it will be validated, and a failure
code returned if it contains the wrong thing\&.  If the file does not exist, it
will be created with a new uuid in it\&.  On success, prints no output\&.
.sp
.sp 1
.in -4
.sp
.ne 2
.mk
\fB-\fB-get=\fIfile\fR\fR\fR
.sp .6
.in +4
If a file is not given, defaults to
\fB/var/lib/dbus/machine-id\fR\&.  If this
\fIfile\fR exists and is valid, the uuid in the file is
printed on \fBstdout\fR\&. Otherwise, the command exits with a
nonzero status\&.
.sp
.sp 1
.in -4
.sp
.ne 2
.mk
\fB-\fB-version\fR\fR
.sp .6
.in +4
Print the version of \fBdbus-uuidgen\fR
.sp
.sp 1
.in -4
.SH "EXAMPLES"
.PP
\fBExample 1: The primary usage of \fBdbus-uuidgen\fR is to run in the post-install script of a D\-Bus package\fR
.PP
.PP
.nf
          \fBdbus-uuidgen\fR --ensure
.fi
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
\fB\fB0\fR\fR
.in +9n
.rt
Application exited successfully
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB\fB>0\fR\fR
.in +9n
.rt
Application exited with failure
.sp
.sp 1
.in -9n
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/bin/dbus-uuidgen\fR\fR
.in +32n
.rt
Executable for \fBdbus-uuidgen\fR
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB\fB/var/lib/dbus/machine-id\fR\fR
.in +32n
.rt
File containing the uuid generated for this machine\&.
.sp
.sp 1
.in -32n
.SH "ATTRIBUTES"
.PP
See
\fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitysystem/library/dbus
Interface stabilityVolatile
.TE
.sp
.SH "SEE ALSO"
.PP
More information can be found at:
.PP
\fBhttp://www\&.freedesktop\&.org/software/dbus/\fR
.PP
\fBdbus-binding-tool\fR(1),
\fBdbus-cleanup-sockets\fR(1),
\fBdbus-daemon\fR(1),
\fBdbus-launch\fR(1),
\fBdbus-monitor\fR(1),
\fBdbus-send\fR(1),
\fBlibdbus-glib-1\fR(3),
\fBattributes\fR(5)
.SH "NOTES"
.PP
For authorship information refer to
\fBhttp://www\&.freedesktop\&.org/software/dbus/doc/AUTHORS\fR\&.
Updated by Brian Cameron, Sun Microsystems Inc\&., 2007\&.
.PP
Please send bug reports to the D\-Bus mailing list or bug
tracker, see
\fBhttp://www\&.freedesktop\&.org/software/dbus/\fR
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
...\" LSARC 2006/368 D-BUS Message Bus System 
