'\" te
.TH fax2ps 1 "26 Mar 2004" "SunOS 5.11" "User Commands"
.SH "NAME"
fax2ps \- convert
a TIFF facsimile to compressed PostScript
.SH "SYNOPSIS"
.PP
\fBfax2ps\fR [\fB\fIoptions\fR\fR] [\fB\fIfile\fR\fR]
.SH "DESCRIPTION"
.PP
\fBfax2ps\fR reads one or more TIFF facsimile image files
and prints a compressed form of PostScript that is suitable for printing on
the standard output\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBH \fIheight\fR\fR\fR
.in +16n
.rt
Use height as the height, in inches, of the output page\&. The
default page height is 11 inches\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBp \fInumber\fR\fR\fR
.in +16n
.rt
Print only the indicated page\&. To print multiple pages, specify
this option as often as required\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBS\fR\fR
.in +16n
.rt
Scale each page
of image data to fill the output page dimensions\&. By default, images are presented
according to the dimension information recorded in the TIFF file\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBW \fIwidth\fR\fR\fR
.in +16n
.rt
Use \fIwidth\fR as the width, in inches,
of the output page\&. The default page width is 8\&.5 inches\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBx \fIresolution\fR\fR\fR
.in +16n
.rt
Use \fIresolution\fR as the horizontal
resolution, in dots per inch, of the image data\&. By default, this value is
taken from the file\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBy \fIresolution\fR\fR\fR
.in +16n
.rt
Use \fIresolution\fR as the vertical
resolution, in lines per inch, of the image data\&. By default, this value is
taken from the file\&.
.sp
.sp 1
.in -16n
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIfile\fR\fR\fR
.in +16n
.rt
The name of the TIFF facsimile image file to be converted
to compressed PostScript\&.
.sp
.sp 1
.in -16n
.SH "EXTENDED DESCRIPTION"
.PP
By default, each page is scaled to reflect the image dimensions and
resolutions stored in the file\&. The -\fBx\fR and -\fBy\fR
options can be used to specify the horizontal and vertical image resolutions,
respectively\&. If the -\fBS\fR option is specified, each page is
scaled to fill an output page\&. The default output page is 8\&.5 by 11 inches\&.
Alternate page dimensions can be specified in inches with the -\fBW\fR
and -\fBH\fR options\&.
.PP
By default, \fBfax2ps\fR generates PostScript for all pages
in the file\&. You can use the -\fBp\fR option to select one or more
pages from a multipage document\&.
.PP
\fBfax2ps\fR generates a compressed form of PostScript that
is optimized for sending pages of text to a PostScript printer attached to
a host through a low-speed link such as a serial line\&. Each output page is
filled with white and then only the black areas are drawn\&. The PostScript
specification of the black drawing operations is optimized by using a special
font that encodes the move-draw operations required to fill the black regions
on the page\&. This compression scheme typically results in a substantially
reduced PostScript description, relative to the straightforward imaging of
the page with a PostScript image operator\&. This algorithm can, however, be
ineffective for continuous-tone and white-on-black images\&. For these images,
it sometimes is more efficient to send the raster bitmap image directly, see \fBtiff2ps\fR(1)\&.
If the destination printer supports PostScript Level II, it is always faster
to just send the encoded bitmap generated by the \fBtiff2ps\fR(1) command\&.
.SS "Diagnostics"
.PP
Some messages about malformed TIFF images come from the TIFF library\&.
.PP
Various messages about badly formatted facsimile images may be generated
due to transmission errors in received facsimile\&. \fBfax2ps\fR
attempts to recover from such data errors by resynchronizing decoding at the
end of the current scanline\&. This can result in long horizontal black lines
in the resultant PostScript image\&.
.SH "EXAMPLES"
.PP
\fBExample 1: Converting the Tiff File test\&.tif to Compressed PostScript\fR
.PP
.PP
.nf
example% \fBfax2ps test\&.tif\fR
.fi
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilityimage/library/libtiff
Interface stabilityUncommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBtiff2ps\fR(1), \fBlibtiff\fR(3)
.SH "NOTES"
.PP
Updated by Breda McColgan, Sun Microsystems Inc\&., 2004\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
...\" LSARC 2003/085 libtiff, libjpeg, and libpng
