'\" te
.TH gobject-query 1 "8 Apr 2003" "SunOS 5.11" "User Commands"
.SH "NAME"
gobject-query \- displays information about \fBgobject\fR types
.SH "SYNOPSIS"
.PP
\fBgobject-query\fR [-\fBr \fItype\fR\fR] [ -\fBi \fIstring\fI\fR\fR\fR | -\fBb \fIstring\fR\fR] [-\fBs \fIint\fR\fR] [-\fBn\fR] [-\fBh\fR] \fIqualifier\fR
.SH "DESCRIPTION"
.PP
\fBgobject-query\fR can be used to display the different types of 
\fBgobjects\fR provided by the \fBglib\fR library
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBb \fIstring\fR\fR\fR
.in +16n
.rt
Specifies the indent \fIstring\fR\&. This option only
applies to the output layout\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBh\fR\fR
.in +16n
.rt
Displays a help message about the \fBgobject-query\fR command, and the
options that you can use with the \fBgobject-query\fR command\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBi \fIstring\fR\fR\fR
.in +16n
.rt
Specifies an incremental indent \fIstring\fR\&. This option
only applies to the output layout\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBn\fR\fR
.in +16n
.rt
Specifies that \fBgobject-query\fR should not descend the type tree\&. This
means that derived types are not displayed\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBr \fItype\fR\fR\fR
.in +16n
.rt
Specifies the root \fItype\fR, for example,
\fBGObject\fR, \fBGParam\fR\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBs \fIint\fR\fR\fR
.in +16n
.rt
Specifies the line spacing\&. This option only applies to the output layout\&.
.sp
.sp 1
.in -16n
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIqualifier\fR\fR\fR
.in +16n
.rt
The following qualifiers are supported:
.sp
.sp
.ne 2
.mk
\fBfroots\fR
.in +9n
.rt
Iterates over the fundamental root
.sp
.sp 2
.in -9n
.sp
.ne 2
.mk
\fBtree\fR
.in +9n
.rt
Prints the type tree
.sp
.sp 1
.in -9n
.sp 0
.in -16n
.SH "EXAMPLES"
.PP
\fBExample 1: Displaying All Types Provided by glib and Derived from GParam\fR
.PP
.PP
.nf
example% \fBgobject-query tree GParam\fR
.fi
.PP
\fBExample 2: Changing the Output Layout\fR
.PP
.PP
.nf
example% \fBgobject-query froots\fR
\f(CW|
`void
|
`GInterface
  |
  `GTypePlugin
\&...\fR
.fi
.PP
.nf
example% \fBgobject-query froots -b foo\fR
\f(CWfoo|
foo`void
foo|
foo`GInterface
foo  |
foo  `GTypePlugin
\&...\fR
.fi
.PP
.nf
example% \fBgobject-query froots -s 5\fR
\f(CW|
|
|
|
|
`void
|
|
|
|
|
`GInterface
\&...
\fR
.fi
.SH "ENVIRONMENT VARIABLES"
.PP
See
\fBenviron\fR(5)
for descriptions of the following environment variables that affect the
execution of \fBgobject-query\fR: NLSPATH\&.
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
\fB\fB0\fR\fR
.in +9n
.rt
Application exited successfully
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB\fB>0\fR\fR
.in +9n
.rt
Application exited with failure
.sp
.sp 1
.in -9n
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/bin/gobject-query\fR\fR
.in +32n
.rt
The command-line executable for the application\&.
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB\fB/usr/share/gtk-doc/html/gobject\fR\fR
.in +32n
.rt
Location of developer documentation
.sp
.sp 1
.in -32n
.SH "ATTRIBUTES"
.PP
See
\fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
AvailabilitySUNWglib2-devel
Interface stabilityCommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBgdk-pixbuf-csource\fR(1),
\fBgdk-pixbuf-query-loaders\fR(1),
\fBgdk-pixbuf-query-loaders\fR(1),
\fBglib-genmarshal\fR(1),
\fBglib-gettextize\fR(1),
\fBglib-mkenums\fR(1),
\fBgtk-query-immodules-2\&.0\fR(1),
\fBgtk-update-icon-cache\fR(1),
\fBlibgdk_pixbuf-2\&.0\fR(3),
\fBattributes\fR(5),
\fBenviron\fR(5),
\fBgnome-interfaces\fR(5)
.SH "NOTES"
.PP
Written by Erwann Chenede, Sun Microsystems Inc\&., 2003\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
