'\" te
.TH tiffcmp 1 "26 Mar 2004" "SunOS 5.11" "User Commands"
.SH "NAME"
tiffcmp \- compare
two TIFF files
.SH "SYNOPSIS"
.PP
\fBtiffcmp\fR [\fB\fIoptions\fR\fR] \fB\fIfile1\&.tif\fR\fR \fB\fIfile2\&.tif\fR\fR
.SH "DESCRIPTION"
.PP
\fBtiffcmp\fR compares the tags and data in two files created
according to the Tagged Image File Format, Revision 6\&.0\&. The schemes used
for compressing data in each file are immaterial when comparing data\&. Files
are compared on a scanline-by-scanline basis after decompression\&. Most directory
tags are checked, notable exceptions are GrayResponseCurve, ColorResponseCurve,
and ColorMap tags\&. Data is not compared if any of the BitsPerSample, SamplesPerPixel,
or ImageWidth values are not equal\&. By default, \fBtiffcmp\fR terminates
if any difference is encountered\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBl\fR\fR
.in +16n
.rt
List each byte
of image data that differs between the files\&.
.sp
.sp 1
.in -16n
.sp
.ne 2
.mk
\fB-\fBt\fR\fR
.in +16n
.rt
Ignore any differences
in directory tags\&.
.sp
.sp 1
.in -16n
.SH "OPERANDS"
.PP
The following operands are supported:
.sp
.ne 2
.mk
\fB\fB\fIfilex\&.tif\fR\fR\fR
.in +16n
.rt
The names of the TIFF files to be compared\&.
.sp
.sp 1
.in -16n
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilityimage/library/libtiff
Interface stabilityUncommitted
.TE
.sp
.SH "SEE ALSO"
.PP
\fBpal2rgb\fR(1),
\fBtiffinfo\fR(1),
\fBtiffcp\fR(1),
\fBtiffmedian\fR(1),
\fBlibtiff\fR(3)
.SH "NOTES"
.PP
Tags that are not recognized by the library are not compared\&. Such tags
may also generate spurious diagnostics\&.
.PP
Updated by Breda McColgan, Sun Microsystems Inc\&., 2004\&.
...\" created by instant / solbook-to-man, Thu 20 Mar 2014, 02:30
...\" LSARC 2003/085 libtiff, libjpeg, and libpng
