-- Disable unused self warnings.
self = false;

-- Allow unused arguments.
unused_args = false;

ignore = {
    -- Allow shadowing; this will be disabled at some point in the future but
    -- for now it raises too many issues.
    "4..",
};

-- Limit line length to 118 characters.
-- TODO: We'll enable this at a later date.
max_line_length = math.huge;
max_code_line_length = math.huge;
max_string_line_length = math.huge;
max_comment_line_length = math.huge;

-- Ignore generated files.
exclude_files = {
    "Libs",
};

globals = {
    "mrp_Prehook_GetColoredName",
    "mrp",
    "mrpLastViewedChangeLogBuild",
    "mrpNotes",
    "mrpSaved",

    "MyRolePlayBrowseFrame_NotesButton",
    "MyRolePlayBrowseFrame_PlayMusicButton",
    "MyRolePlayBrowseFrame",
    "MyRolePlayBrowseFrameAScrollFrame",
    "MyRolePlayBrowseFrameAScrollFrameScrollBar",
    "MyRolePlayBrowseFrameBScrollFrame",
    "MyRolePlayBrowseFrameBScrollFrameScrollBar",
    "MyRolePlayBrowseFrameCScrollFrame",
    "MyRolePlayBrowseFrameCScrollFrameScrollBar",
    "MyRolePlayBrowseFrameDScrollFrame",
    "MyRolePlayBrowseFrameDScrollFrameScrollBar",
    "MyRolePlayBrowseFrameEScrollFrame",
    "MyRolePlayBrowseFrameEScrollFrameScrollBar",
    "MyRolePlayBrowseFrameInset",
    "MyRolePlayBrowseFrameTab1",
    "MyRolePlayBrowseFrameTab2",
    "MyRolePlayBrowseFrameTab3",
    "MyRolePlayBrowseFrameTitleText",
    "MyRolePlayButton",
    "MyRolePlayChangeLogFrame",
    "MyRolePlayChangeLogHTMLFrame",
    "MyRolePlayChangeLogScrollFrame",
    "MyRolePlayChangeLogScrollFrameScrollBar",
    "MyRolePlayCharacterFrame_ColourButton",
    "MyRolePlayCharacterFrame_EyeColourButton",
    "MyRolePlayCharacterFrame_Profile_Dropdown",
    "MyRolePlayCharacterFrame_RestoreDefaultColourButtonEyes",
    "MyRolePlayCharacterFrame_RestoreDefaultColourButtonName",
    "MyRolePlayCharacterFrame",
    "MyRolePlayCharacterFrameCloseButton",
    "MyRolePlayCharacterFrameInset",
    "MyRolePlayCharacterFramePortrait",
    "MyRolePlayComboEditFrame",
    "MyRolePlayComboEditFrameComboBoxButton",
    "MyRolePlayComboEditFrameComboBoxText",
    "MyRolePlayDescriptionPreviewFrame",
    "MyRolePlayDescriptionPreviewFrameScrollFrame",
    "MyRolePlayEditFrame",
    "MyRolePlayGlanceEditFrame",
    "MyRolePlayGlanceFrame",
    "MyRolePlayGlanceFrameTitleText",
    "MyRolePlayMultiEditFrame_DescripInsertColourButton",
    "MyRolePlayMultiEditFrame_DescripInsertHeader1Button",
    "MyRolePlayMultiEditFrame_DescripInsertParagraphButton",
    "MyRolePlayMultiEditFrame_EditBox",
    "MyRolePlayMultiEditFrame_FormattingToolsSubtitle",
    "MyRolePlayMultiEditFrame_InsertIconButton",
    "MyRolePlayMultiEditFrame_InsertImageButton",
    "MyRolePlayMultiEditFrame_LinkInsertButton",
    "MyRolePlayMultiEditFrame_PreviewProfileButton",
    "MyRolePlayMultiEditFrame",
    "MyRolePlayMultiEditFrameScrollFrame",
    "MyRolePlayNotesFrame",
    "MyRolePlayNotesFrameEditBox",
    "MyRolePlayNotesFrameHeaderFontString",
    "MyRolePlayNotesFrameInset",
    "MyRolePlayNotesFrameScrollFrame",
    "MyRolePlayNotesFrameScrollFrameScrollBar",
    "MyRolePlayNotesFrameTitleText",
    "MyRolePlayNoTraits",
    "MyRolePlayOptionsPanel_GlancePosition",
    "MyRolePlayOptionsPanel_GlancePositionButton",
    "MyRolePlayOptionsPanel_GlancePositionDropDown",
    "MyRolePlayOptionsPanel_GlancePositionText",
    "MyRolePlayOptionsPanel_HeaderColourTexture",
    "MyRolePlayOptionsPanel_HeightUnit",
    "MyRolePlayOptionsPanel_HeightUnitButton",
    "MyRolePlayOptionsPanel_HeightUnitDropDown",
    "MyRolePlayOptionsPanel_HeightUnitText",
    "MyRolePlayOptionsPanel_TTStyle",
    "MyRolePlayOptionsPanel_TTStyleButton",
    "MyRolePlayOptionsPanel_TTStyleDropDown",
    "MyRolePlayOptionsPanel_TTStyleText",
    "MyRolePlayOptionsPanel_WeightUnit",
    "MyRolePlayOptionsPanel_WeightUnitButton",
    "MyRolePlayOptionsPanel_WeightUnitDropDown",
    "MyRolePlayOptionsPanel_WeightUnitText",
    "MyRolePlayOptionsPanel",
    "MyRolePlayTraitsEditFrame",
    "MyRolePlayTraitsEditScrollFrame",
    "MyRolePlayTraitsEditScrollFrameScrollBar",

    "MRPIconSelect_ClearIconButton",
    "MRPIconSelect",
    "MRPIconSelectSearchBox",
    "MRPImageSelect",
    "MRPImageSelectSearchBox",
    "MRPMusicSelect",
    "MRPMusicSelectSearchBox",

    "mrp_DescripInsertColourChangedCallback",
    "mrp_EyeColourChangedCallback",
    "mrp_iconselector_show",
    "mrp_imageselector_show",
    "mrp_MSPBrowserCallback",
    "mrp_MSPButtonCallback",
    "mrp_MSPExchangeCallback",
    "mrp_MSPGlancePreviewCallback",
    "mrp_MSPTooltipCallback",
    "mrp_MSPUpdateCallback",
    "mrp_musicselector_show",
    "mrp_NameColourChangedCallback",

    "g_trp_icon_list_data",
    "g_trp_image_list_data",

    "BINDING_HEADER_MYROLEPLAY",
    "BINDING_NAME_CHARACTER_SHEET",
    "GetColoredName",
    "SLASH_MRP1",
    "SLASH_MRP2",
    "SlashCmdList",
    "StaticPopupDialogs",

    "CharacterFrame_TabBoundsCheck", -- CharacterFrame integration.
    "CharacterFrame", -- Modifies fields.
    "ColorPickerFrame", -- Modifies fields.
};

read_globals = {
    -- AddOn integrations.
    "AddOnSkins",
    "ElvUI",
    "ItemRack",
    "ItemRackUser",
    "Outfitter",
    "Perl_Target_StatsFrame",
    "SUFUnittarget",
    "TRP3_Characters",
    "TRP3_Profiles",
    "XPerl_Target",
    "xrpAccountSaved",
    "xrpSaved",
};

-- Add exceptions for external libraries.
std = "lua51+libstub+libmsp+wow+wowstd"

stds.libstub = {
    read_globals = {
        "LibStub",
    },
};

stds.libmsp = {
    read_globals = {
        msp = {
            fields = {
                "AddFieldsToTooltip",
                "Request",
                "Update",

                "char",
                "myver",
                "protocolversion",
            },
        },
    },

    globals = {
        msp = {
            fields = {
                callback = {
                    fields = {
                        "dataload",
                        "received",
                        "status",
                        "updated",
                    },
                },

                "my",
            },
        },
    },
};

stds.wow = {
    read_globals = {
        C_EquipmentSet = {
            fields = {
                "GetEquipmentSetInfo",
            },
        },

        C_Timer = {
            fields = {
                "After",
            },
        },

        C_UI = {
            fields = {
                "Reload",
            },
        },

        "ACCEPT",
        "Ambiguate",
        "BEAR_FORM",
        "BlizzardOptionsPanel_OnLoad",
        "BlizzardOptionsPanel_RegisterControl",
        "ButtonFrameTemplate_ShowButtonBar",
        "CANCEL",
        "CAT_FORM",
        "CharacterFrame_Collapse",
        "CharacterFrame_Expand",
        "CHARACTERFRAME_SUBFRAMES",
        "CharacterFrame_UpdatePortrait",
        "CharacterFrame",
        "CharacterFrame",
        "CharacterFrameInset",
        "CharacterFrameInsetRight",
        "CharacterFramePortrait",
        "CharacterFrameTab1",
        "CharacterFrameTab2",
        "CharacterFrameTab3",
        "CharacterFrameTab4",
        "CharacterFrameTitleText",
        "CharacterNameText",
        "CharacterNameText",
        "CharacterStatsPane",
        "ChatEdit_FocusActiveWindow",
        "ChatFrame_AddMessageEventFilter",
        "ChatTypeInfo",
        "CLOSE",
        "ColorPickerFrame",
        "ColorPickerOkayButton",
        "CONTROLTYPE_CHECKBOX",
        "CONTROLTYPE_DROPDOWN",
        "CONTROLTYPE_SLIDER",
        "CreateAtlasMarkup",
        "CreateColor",
        "CreateFont",
        "CreateFrame",
        "CreateTextureMarkup",
        "DEFAULT_CHAT_FRAME",
        "DisableAddOn",
        "DropDownList1",
        "EasyMenu",
        "EditBox_ClearFocus",
        "EditBox_ClearHighlight",
        "EditBox_HighlightText",
        "FACTION_BAR_COLORS",
        "FauxScrollFrame_GetOffset",
        "FauxScrollFrame_OnVerticalScroll",
        "FauxScrollFrame_Update",
        "GameFontHighlight",
        "GameFontNormal",
        "GameFontNormalHuge",
        "GameFontNormalHuge3",
        "GameFontNormalLarge",
        "GameTooltip_AddBlankLinesToTooltip",
        "GameTooltip_AddColoredLine",
        "GameTooltip_Hide",
        "GameTooltip_SetDefaultAnchor",
        "GameTooltip",
        "GetAddOnEnableState",
        "GetAddOnInfo",
        "GetAddOnMetadata",
        "GetBuildInfo",
        "GetCVar",
        "GetGuildInfo",
        "GetLocale",
        "GetPlayerInfoByGUID",
        "GetRealmName",
        "GetShapeshiftFormID",
        "GetTime",
        "HideDropDownMenu",
        "hooksecurefunc",
        "InterfaceOptions_AddCategory",
        "InterfaceOptionsFrame_OpenToCategory",
        "InterfaceOptionsFramePanelContainer",
        "IsAddOnLoaded",
        "IsGMClient",
        "IsReferAFriendLinked",
        "IsTrialAccount",
        "IsVeteranTrialAccount",
        "MOONKIN_FORM",
        "NO",
        "nop",
        "OKAY",
        "PANEL_DEFAULT_WIDTH",
        "PanelTemplates_DeselectTab",
        "PanelTemplates_SelectTab",
        "PanelTemplates_SetDisabledTabState",
        "PanelTemplates_SetNumTabs",
        "PanelTemplates_SetTab",
        "PanelTemplates_TabResize",
        "PaperDollFrame",
        "PlaySound",
        "PlaySoundFile",
        "RAID_CLASS_COLORS",
        "ScrollBar_AdjustAnchors",
        "ScrollFrame_OnScrollRangeChanged",
        "ScrollFrame_OnUpdate",
        "ScrollingEdit_OnCursorChanged",
        "ScrollingEdit_OnTextChanged",
        "ScrollingEdit_OnUpdate",
        "SetPortraitTexture",
        "SetPortraitToTexture",
        "SetPortraitToTexture",
        "StaticPopup_Show",
        "StopSound",
        "TargetFrame",
        "ToggleCharacter",
        "ToggleDropDownMenu",
        "TOOLTIP_DEFAULT_COLOR",
        "UIDropDownMenu_AddButton",
        "UIDropDownMenu_CreateInfo",
        "UIDropDownMenu_DisableDropDown",
        "UIDropDownMenu_EnableDropDown",
        "UIDropDownMenu_Initialize",
        "UIDropDownMenu_SetSelectedID",
        "UIDropDownMenu_SetSelectedValue",
        "UIDropDownMenu_SetWidth",
        "UIParent",
        "UnitAffectingCombat",
        "UnitBuff",
        "UnitCanAttack",
        "UnitClass",
        "UnitExists",
        "UnitFactionGroup",
        "UnitFullName",
        "UnitGUID",
        "UnitInPhase",
        "UnitIsAFK",
        "UnitIsCharmed",
        "UnitIsDeadOrGhost",
        "UnitIsDND",
        "UnitIsInMyGuild",
        "UnitIsPlayer",
        "UnitIsPVP",
        "UnitIsUnit",
        "UnitLevel",
        "UnitName",
        "UnitOnTaxi",
        "UnitPlayerControlled",
        "UnitPVPName",
        "UnitRace",
        "UnitReaction",
        "UnitSex",
        "UNKNOWN",
        "UNKNOWNOBJECT",
        "UpdateUIPanelPositions",
        "WOW_PROJECT_CLASSIC",
        "WOW_PROJECT_ID",
        "WOW_PROJECT_MAINLINE",
        "YES",
    },
};

stds.wowstd = {
    read_globals = {
        string = {
            fields = {
                "join",
                "split",
                "trim",
            },
        },

        table = {
            fields = {
                "wipe",
            },
        },

        "ceil",
        "floor",
        "format",
        "getglobal",
        "gsub",
        "max",
        "min",
        "strconcat",
        "strfind",
        "strjoin",
        "strlower",
        "strmatch",
        "strsplit",
        "strsplit",
        "strsub",
        "strtrim",
        "tconcat",
        "tContains",
        "tinsert",
        "wipe",
    },
};
