globals = {'LibStub', 'UIDROPDOWNMENU_OPEN_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_MENU', 'COMMUNITY_UIDD_REFRESH_PATCH_VERSION', 'COMMUNITY_UIDD_REFRESH_PATCH_VERSION', 'SLASH_RENOVATE1', 'LE_GARRISON_TYPE_8_0', 'LE_FOLLOWER_TYPE_GARRISON_8_0', 'GARRISON_LONG_MISSION_TIME', 'GARRISON_LONG_MISSION_TIME_FORMAT', 'WAR_MISSIONS', 'WAR_FOLLOWERS', 'WINTERGRASP_IN_PROGRESS', 'GARRISON_MISSION_ADDED_TOAST1', 'BONUS_ROLL_REWARD_MONEY', 'XP', 'ARTIFACT_POWER', 'OTHER', 'HIGHLIGHT_FONT_COLOR', 'COPPER_PER_GOLD', 'Fancy18Font', 'Game13Font', 'Game13FontShadow', 'hooksecurefunc', 'issecurevariable', 'FriendsFrame', 'FriendsTabHeader'}
ignore = {'self', '532'}
max_line_length = false
self = false
