/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.5

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();
int nLaw = GetAlignmentLawChaos(oPC);

if (nLaw == ALIGNMENT_LAWFUL)
    AdjustAlignment(oPC, ALIGNMENT_CHAOTIC, 50);
else if (nLaw == ALIGNMENT_CHAOTIC)
    AdjustAlignment(oPC, ALIGNMENT_LAWFUL, 50);

AdjustAlignment(oPC, ALIGNMENT_EVIL, 100);

}

