# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/babel-source/all/babel-source.rbi
#
# babel-source-5.8.35
module Babel
end
module Babel::Source
end
