# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/backports/all/backports.rbi
#
# backports-3.15.0
class String
  def camelize(first_letter = nil); end
  def constantize; end
  def dasherize; end
  def demodulize; end
  def underscore; end
end
