// BASIC RULES
start : "`" char* "`"

?char : NON_ESCAPE    -> ascii
      | "\\`"         -> quote
      | "\\\\"        -> backslash
      | "\\/"         -> solidus
      | "\\b"         -> backspace
      | "\\f"         -> formfeed
      | "\\n"         -> newline
      | "\\r"         -> return_line
      | "\\t"         -> tab
      | "\\x" hex

hex   : HEX HEX


// TERMINALS
NON_ESCAPE : /[^`\\\n\x00-\x1F\x7F-\U00100000]+/
HEX        : /[a-fA-F0-9]/
