%import common.LF -> _NL

COMMENT: "#" /[^\n]/* _NL
%ignore COMMENT

_WS: /[ \t]+/

start: para (_NL+ para)* _NL*

_value: /[^ \t\n][^\n]*/

// Field names are ASCII in the ranges stated by the deb822 man page,
// but the first character cannot be # nor -
name: /[\x21\x22\x24-\x2c\x2e-\x39\x3b-\x7e][\x21-\x39\x3b-\x7e]*/

data: _value? (_NL _WS _value)* _NL

field: name ":" _WS? data

para: field+
