void main()
{
object oPC = GetEnteringObject();

SendMessageToPC(oPC, "You can hear the nearby river passing by just outside the grate, the sewer water flowing out and presumably into the river itself. Nearby, there is a ladder that leads up to a round hole, covered with a metal plate. This is likely a service exit near the river, and you'd guess that climbing the ladder will put you out somewhere around Star Bridge.");
}