start : validation_struct*

validation_struct : "validation" name "{" declaration*  "}"

declaration : variable ":=" rule ";"

rule : "NO_REQUIREMENT"
     | function_name "(" param ["," param]+ ")"
     | "current" operator value


function_name : FUNCTION_NAME

operator : "=="
         | "!="

name : WORD
variable : WORD
param : WORD
value : WORD

FUNCTION_NAME : /[A-Z_]+/
WORD : /[a-zA-Z0-9]+/


%import common.WS
%ignore WS