start: expr*

?expr: integer
    | string
    | atom
    | sigil_string
    | name
    | s_expr
    | vector
    | quoted

quoted: "&" expr
s_expr: "(" expr* ")"
vector: "[" expr* "]"

string: ESCAPED_STRING
atom: ":" IDENTIFIER
name: IDENTIFIER
integer: /[+-]?(0|[1-9][0-9]*)/
sigil_string: "~" IDENTIFIER ESCAPED_STRING


IDENTIFIER: /(?![+-]?[0-9])[-+*\/%=<>_!?a-zA-Z0-9]+/

COMMENT: /;.*/
COMMA: ","

%import common.WS
%ignore WS
%ignore COMMENT
%ignore COMMA

%import common.ESCAPED_STRING