?start			: expr
?expr			: addition
?addition		: expr "+" expr			-> _add
				| expr "-" expr			-> _sub
				| multiplication
?multiplication	: expr "*" expr			-> _mul
				| expr "/" expr			-> _div
				| power
?power			: expr "^" expr			-> _exp
				| atom
?atom			: "(" expr ")"
				| CNAME "(" expr ")"	-> _func_call
				| NUMBER				-> _num
				| "-" expr				-> _negate

%import common.NUMBER
%import common.CNAME
%import common.WS
%ignore WS
