variant : p_variant

// g_variant : ACCESSION ":g." g_interval
p_variant : ACCESSION ":p." p_posedit


p_posedit     : p_posedit_sub
              | "=" -> p_posedit_identical
              | "0" -> p_posedit_no_protein
              | "?" -> p_posedit_unknown

p_posedit_sub : p_pos (AA1 | TERM1)
              | p_pos "=" -> p_posedit_sub_identical
              | p_pos "?" -> p_posedit_sub_unknown

p_pos : AA1 INT

AA1   : /[ACDEFGHIKLMNPQRSTVWYBZXU]/
TERM1 : /[X*]/

ACCESSION : /[-\w]+(.\d+)?/
%import common.INT