start: keyword_card+
     | // empty
keyword_card: KEYWORD ("," param)* [_NEWLINE data_line*]
KEYWORD: "*" WORD (WS_INLINE WORD)*
param: KEY "=" value
     | KEY
KEY: WORD
value: WORD
     | INT
     | CNAME
     | PATH
PATH: /.+\/[^\/]+/

data_line: value ("," value)*

COMMENT: "**" /.*/

_NEWLINE: NEWLINE

%import common.WORD
%import common.CNAME
%import common.INT
%import common.NEWLINE
%import common.WS
%import common.WS_INLINE
%ignore WS
%ignore COMMENT
