?start: value
?value: object
      | array
      | string
      | DEC_NUMBER      -> number
      | "true"             -> true
      | "false"            -> false
      | "null"             -> null
array  : "[" [value ("," value)*] "]"
object : "{" [pair ("," pair)*] "}"
pair   : string ":" value
string : ESCAPED_STRING

DEC_NUMBER: /((\d+\.\d*|\.\d+)(e[-+]?\d+)?|\d+(e[-+]?\d+))|(\d+)/i
%import common.ESCAPED_STRING
%import common.WS
%ignore WS
