?start: value

?value: object
      | array
      | string
      | SIGNED_FLOAT    -> floating
      | SIGNED_INT      -> integer
      | "true"          -> true
      | "false"         -> false
      | "null"          -> null

array  : "[" [value ("," value)*] "]"
object : "{" [object_entry ("," object_entry)*] "}"
object_entry   : string ":" value

string : ESCAPED_STRING

%import common.ESCAPED_STRING
%import common.SIGNED_FLOAT
%import common.SIGNED_INT
%import common.WS

%ignore WS
