(**
SimSoC-Cert, a toolkit for generating certified processor simulators
See the COPYRIGHTS and LICENSE files.

Coq representation of a C program automatically generated by Simgen.
*)

Require Import ZArith Cnotations.

Open Scope Z_scope.

(* identifiers *)

Open Scope positive_scope.
Definition hi := 1.
Definition lo := 2.
Definition struct___int64 := 3.
Definition mem := 4.
Definition _end := 5.
Definition size := 6.
Definition begin := 7.
Definition SLv6_MMU := 8.
Definition background := 9.
Definition mode := 10.
Definition T_flag := 11.
Definition F_flag := 12.
Definition I_flag := 13.
Definition A_flag := 14.
Definition E_flag := 15.
Definition GE3 := 16.
Definition GE2 := 17.
Definition GE1 := 18.
Definition GE0 := 19.
Definition J_flag := 20.
Definition Q_flag := 21.
Definition V_flag := 22.
Definition C_flag := 23.
Definition Z_flag := 24.
Definition N_flag := 25.
Definition SLv6_StatusRegister := 26.
Definition v_bit := 27.
Definition u_bit := 28.
Definition ee_bit := 29.
Definition SLv6_SystemCoproc := 30.
Definition jump := 31.
Definition pc := 32.
Definition und_regs := 33.
Definition abt_regs := 34.
Definition svc_regs := 35.
Definition irq_regs := 36.
Definition fiq_regs := 37.
Definition user_regs := 38.
Definition id := 39.
Definition cp15 := 40.
Definition spsrs := 41.
Definition cpsr := 42.
Definition mmu_ptr := 43.
Definition SLv6_Processor := 44.
Definition gvars := 45.
Definition main := 46.
Definition d := 47.
Definition cond := 48.
Definition address := 49.
Definition read_byte := 50.
Definition proc := 51.
Definition set_reg_or_pc := 52.
Definition ConditionPassed := 53.
Definition LDRB := 54.
Close Scope positive_scope.

(* structs and unions *)

Definition typ_struct_SLv6_SystemCoproc := 
F[
  ee_bit -: uint8; 
  u_bit -: uint8; 
  v_bit -: uint8].

Definition typ_SLv6_SystemCoproc := Tstruct SLv6_SystemCoproc typ_struct_SLv6_SystemCoproc.

Definition typ_struct_SLv6_StatusRegister := 
F[
  N_flag -: uint8; 
  Z_flag -: uint8; 
  C_flag -: uint8; 
  V_flag -: uint8; 
  Q_flag -: uint8; 
  J_flag -: uint8; 
  GE0 -: uint8; 
  GE1 -: uint8; 
  GE2 -: uint8; 
  GE3 -: uint8; 
  E_flag -: uint8; 
  A_flag -: uint8; 
  I_flag -: uint8; 
  F_flag -: uint8; 
  T_flag -: uint8; 
  mode -: int32; 
  background -: uint32].

Definition typ_SLv6_StatusRegister := Tstruct SLv6_StatusRegister typ_struct_SLv6_StatusRegister.

Definition typ_struct_SLv6_MMU := 
F[
  begin -: uint32; 
  size -: uint32; 
  _end -: uint32; 
  mem -: `*` uint8].

Definition typ_SLv6_MMU := Tstruct SLv6_MMU typ_struct_SLv6_MMU.

Definition typ_struct_SLv6_Processor := 
F[
  mmu_ptr -: `*` typ_SLv6_MMU; 
  cpsr -: typ_SLv6_StatusRegister; 
  spsrs -: Tarray typ_SLv6_StatusRegister 5; 
  cp15 -: typ_SLv6_SystemCoproc; 
  id -: uint32; 
  user_regs -: Tarray uint32 16; 
  fiq_regs -: Tarray uint32 7; 
  irq_regs -: Tarray uint32 2; 
  svc_regs -: Tarray uint32 2; 
  abt_regs -: Tarray uint32 2; 
  und_regs -: Tarray uint32 2; 
  pc -: `*` uint32; 
  jump -: uint8].

Definition typ_SLv6_Processor := Tstruct SLv6_Processor typ_struct_SLv6_Processor.

(* expression types *)

Definition T1 := Tfunction T[`*` typ_SLv6_StatusRegister; int32] int8.
Definition T2 := `*` typ_SLv6_Processor.
Definition T3 := typ_SLv6_Processor.
Definition T4 := typ_SLv6_StatusRegister.
Definition T5 := `*` typ_SLv6_StatusRegister.
Definition T6 := int32.
Definition T7 := int8.
Definition T8 := Tfunction T[`*` typ_SLv6_Processor; uint8; uint32] void.
Definition T9 := uint8.
Definition T10 := Tfunction T[`*` typ_SLv6_MMU; uint32] uint8.
Definition T11 := uint32.
Definition T12 := void.

(* global variables *)

Definition gv_gvars :=
  {| gvar_info := Tarray uint8 0;
     gvar_init := [Init_int8 0];
     gvar_readonly := false;
     gvar_volatile := false |}.

Definition global_variables : list (prod ident (globvar type)) := [(gvars,gv_gvars)].

(* functions *)

Definition fun_internal_LDRB :=
  {| fn_return := void;
     fn_params := [
proc -: `*` typ_SLv6_Processor; 
address -: uint32; 
cond -: int32; 
d -: uint8];
     fn_vars := [];
     fn_body :=
`if (call (\ConditionPassed`:T1) E[&((`*(\proc`:T2)`:T3)|cpsr`:T4)`:T5; \cond`:T6] T7)
then (call (\set_reg_or_pc`:T8) E[\proc`:T2; \d`:T9; (call (\read_byte`:T10) E[\address`:T11] T9)] T12)
else skip |}.

Definition fun_LDRB :=
  (LDRB, Internal fun_internal_LDRB).

Definition functions : list (prod ident fundef) := [fun_LDRB].

(* program *)

Definition p :=
  {| prog_funct := functions;
     prog_main := main;
     prog_vars := global_variables |}.
