value: NUMBER
        | STRING
        | SYMBOL
        | "#t" | "true" | "🙂" 
        | "#f" | "false" | "🙁"
        | sexpr
        | quoted
        | infix
        | list
        | dict
        | pair
        | value

sexpr : "(" [value (" " value)*] ")"

quoted : "'" value

infix : "[" value value value "]"

list : "$(" value* ")"

dict : "{" pair* "}"

pair: value "->" value

NUMBER: /(\d+)|(\d+\.\d+)/
STRING: /\"[\w\s\n]*\"/
SYMBOL: /([\w+\-=*])*/

WS: /\s+/
%ignore WS