?sentence: equivalence
?equivalence: implication
	| equivalence "<=>"  implication
?implication: or_
	| or_ "=>" implication
?or_: and_
	| or_ "|" and_
	| or_ "\\/" and_
?and_: not_
	| and_ "&" not_
	| and_ "/\\" not_	
?not_: symbol
	| "~" not_ -> not_
?symbol: par
	| atom		-> atom
	| "True"	-> true
	| "False"	-> false
?par: "(" sentence ")"
	| "[" sentence "]"

?atom: /[a-zA-Z_'][a-zA-Z0-9_']*/

%import common.WS

%ignore WS