# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mini_backtrace/all/mini_backtrace.rbi
#
# mini_backtrace-0.1.3
module Minitest
  def self.filter_backtrace_with_rails(bt); end
  def self.filter_backtrace_without_rails(bt); end
end
