package java.lang;

/**
 * 
 * @author cym
 *
 */
public final class RemotingServiceFactory {
	private static final RemotingServiceFactory INSTANCE = new RemotingServiceFactory();
	private RemotingServiceFactory(){
		
	}
	
	public static final RemotingServiceFactory getInstance(){
		return INSTANCE;
	}
	
	public Object getService(Class<?> clazz){
		return clazz.prototype;
	}
}
