start : assignment
      | commands
      | eps

assignment : NAME "=" string

commands : command ("|" command)*

eps : WS*

command : COMMAND_NAME args

args : string*

string : "'" SINGLE_QUOTE? "'"
       | "\"" DOUBLE_QUOTE? "\""
       | WORD

NAME : /[a-zA-Z_][a-zA-Z0-9_]*/
COMMAND_NAME : /[\/\\a-zA-Z_-][\/\\a-zA-Z0-9_-]*/
SINGLE_QUOTE : /[^']+/
DOUBLE_QUOTE : /[^\"]+/
WORD :  /[^ '|\"]+/
WS : /[ \t]+/
%ignore WS
