start : atom ( chain | branch)*
chain : ( bond? ( atom | RING ) )+
branch : "(" bond?  start+ ")"
atom : ORGANIC | AROMATIC | ELEMENT | "[" ISOTOPE? ( "se" | "as" | AROMATIC | ELEMENT | WILDCARD ) chiral? HCOUNT? CHARGE? CLASS? "]" | WILDCARD
chiral : ( "@" ( "@" | ( "TH" | "AL" ) /[1-2]/ | "SP" /[1-3]/ | "TB" ( "1" DIGIT? | "2" "0"? | /[3-9]/ ) | "OH" ( ( "1" | "2" ) DIGIT? | "3" "0"? | /[4-9]/ ) )? )?
bond : SINGLE_BOND | DOUBLE_BOND | TRIPLE_BOND | AROMATIC_BOND | STEREOISOMER_BOND_CIS | STEREOISOMER_BOND_TRANS | DISCONNECTED_STRUCTURE

SINGLE_BOND : "-"
DOUBLE_BOND : "="
TRIPLE_BOND : "#"
AROMATIC_BOND : "*"
STEREOISOMER_BOND_CIS : "/"
STEREOISOMER_BOND_TRANS : "\\"
DISCONNECTED_STRUCTURE : "."
ISOTOPE :  /[1-9]/ DIGIT? DIGIT?
ORGANIC : "B" | "Br" | "C" | "Cl" | "N" | "O" | "P" | "S" | "F" | "I"
AROMATIC : "b" | "c" | "n" | "o" | "p" | "s"
ELEMENT : "H" | "He" | "Li" | "Be" | "B" | "C" | "N" | "O" | "F" | "Ne" | "Na" | "Mg" | "Al" | "Si" | "P" | "S" | "Cl" | "Ar" | "K" | "Ca" | "Sc" | "Ti" | "V" | "Cr" | "Mn" | "Fe" | "Co" | "Ni" | "Cu" | "Zn" | "Ga" | "Ge" | "As" | "Se" | "Br" | "Kr" | "Rb" | "Sr" | "Y" | "Zr" | "Nb" | "Mo" | "Tc" | "Ru" | "Rh" | "Pd" | "Ag" | "Cd" | "In" | "Sn" | "Sb" | "Te" | "I" | "Xe" | "Cs" | "Ba" | "Hf" | "Ta" | "W" | "Re" | "Os" | "Ir" | "Pt" | "Au" | "Hg" | "Tl" | "Pb" | "Bi" | "Po" | "At" | "Rn" | "Fr" | "Ra" | "Rf" | "Db" | "Sg" | "Bh" | "Hs" | "Mt" | "Ds" | "Rg" | "Cn" | "Fl" | "Lv" | "La" | "Ce" | "Pr" | "Nd" | "Pm" | "Sm" | "Eu" | "Gd" | "Tb" | "Dy" | "Ho" | "Er" | "Tm" | "Yb" | "Lu" | "Ac" | "Th" | "Pa" | "U" | "Np" | "Pu" | "Am" | "Cm" | "Bk" | "Cf" | "Es" | "Fm" | "Md" | "No" | "Lr"
RING : ( "%" DIGIT? )? DIGIT
CHARGE : "-" ( /[-02-9]/ | "1" /[0-5]/? ) ? | "+" ( /[+02-9]/ | "1" /[0-5]/? ) ?
HCOUNT : "H" DIGIT?
CLASS : ":" DIGIT+
DIGIT: /[0-9]/
WILDCARD : "*"
DOT : "."
