// soc_system_trace_wrapper_0.v

// This file was auto-generated from altera_trace_wrapper_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module soc_system_trace_wrapper_0 #(
		parameter IN_DWIDTH        = 32,
		parameter OUT_DWIDTH       = 32,
		parameter NUM_PIPELINE_REG = 1
	) (
		input  wire        clock_sink_clk,        //     clock_sink.clk
		input  wire        reset_sink_reset_n,    //     reset_sink.reset_n
		input  wire [31:0] h2f_tpiu_data,         //       h2f_tpiu.data
		output wire        h2f_tpiu_clk_ctl,      //               .clk_ctl
		output wire        h2f_tpiu_clkin,        //               .clkin
		input  wire        f2h_clk_in_clk_ctl,    //     f2h_clk_in.clk_ctl
		input  wire        f2h_clk_in_clk,        //               .clk
		output wire        trace_clk_out_clk,     //  trace_clk_out.clk
		output wire [31:0] trace_data_out_export  // trace_data_out.export
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (IN_DWIDTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					in_dwidth_check ( .error(1'b1) );
		end
		if (OUT_DWIDTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					out_dwidth_check ( .error(1'b1) );
		end
		if (NUM_PIPELINE_REG != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					num_pipeline_reg_check ( .error(1'b1) );
		end
	endgenerate

	altera_trace #(
		.NUM_PIPELINE_REG (1),
		.IN_DWIDTH        (32),
		.OUT_DWIDTH       (32),
		.ADD_FEATURE      (1)
	) altera_trace_inst (
		.h2f_tpiu_clock_out     (clock_sink_clk),        //     clock_sink.clk
		.trace_clkout           (trace_clk_out_clk),     //  trace_clk_out.clk
		.h2f_tpiu_reset_n       (reset_sink_reset_n),    //     reset_sink.reset_n
		.h2f_tpiu_data          (h2f_tpiu_data),         //       h2f_tpiu.data
		.f2h_tpiu_clock_out_ctl (h2f_tpiu_clk_ctl),      //               .clk_ctl
		.f2h_tpiu_clock_out     (h2f_tpiu_clkin),        //               .clkin
		.trace_clk_ctl          (f2h_clk_in_clk_ctl),    //     f2h_clk_in.clk_ctl
		.trace_clkin            (f2h_clk_in_clk),        //               .clk
		.trace_dataout          (trace_data_out_export), // trace_data_out.export
		.data_gpio              (),                      //    (terminated)
		.clk_gpio               (),                      //    (terminated)
		.reset_gpio             ()                       //    (terminated)
	);

endmodule
