start : expression*

expression : single_quote_expression
           | double_quote_expression
           | substitution
           | STRING

single_quote_expression : /'[^']*'/

double_quote_expression : "\"" double_quote_internal_expression* "\""

double_quote_internal_expression : internal_substitution
                                 | INTERNAL_STRING

substitution : "$" NAME
internal_substitution : "$" NAME

STRING : /[^"'$]+/
INTERNAL_STRING : /[^"$]+/
NAME : /[a-zA-Z_][a-zA-Z0-9_]*/
