?value : header? TERRAIN

terrain : TERRAIN

TERRAIN : /(([\^\#*_+-~])+\n)+/

header : "@" [assignment ("|" assignment)*]
assignment : assignment_colour | assignment_size
assignment_colour : ("air"i | "water"i) "=" colour
assignment_size : "size"i "=" NUMBER

colour : "(" [NUMBER "," NUMBER "," NUMBER ("," NUMBER)?] ")"

NUMBER : /[0-9]/+

COMMENT : ";" /[^\n]/*

%import common.WS
%ignore WS
%ignore COMMENT
