package test;

import org.w3c.event.MouseEvent;
import org.w3c.event.MouseEventHandler;
 
public class Test implements Page{
<%
	<html xmlns:lark="http://www.lark.org/2012" xmlns:xlink="http://www.w3.org/1999/xlink">
		<head>  
		</head>
		<body > 
			<input style.font-size={Binding} onclick="click"/>  
		</body>  
	</html>   
%>
	   
	MouseEventHandler click= (MouseEvent e)->{ 
		
	};
	
	String name;
	
}
 