package collection;

import java.util.ArrayList;
import java.util.Collection; 
import java.util.List;
import java.util.ObservableCollection;

import org.w3c.event.Event;
import org.w3c.event.EventHandler;
import org.w3c.event.MouseEvent;
import org.w3c.event.MouseEventHandler;
 
public class Test2 implements Page, INotifyPropertyChanged {
	<%
	<html xmlns:lark = "http://www.lark.org/2012"> 
		<head> 
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
			<style>
			.rect {
			    border: 5px solid red;
			}  
			</style>
		</head>
		<body style="2121"> 
			<Iterator items={Binding property="persons"}>
				<h1 textContent = {Binding property="name" context="current"} />
			</Iterator>
			
		</body> 
	</html>
	%>

	/**
	*@see Test2#name
	 */ 
	public Test2(){
		_persons.add(new Person("1", "张三", "山东高密", 65));
		_persons.add(new Manager("4", "经理3", "山东高密2", 65));
		_persons.add(new Person("2", "张三1", "山东高密1", 65));
		_persons.add(new Person("3", "张三2", "山东高密2", 65));
		_persons.add(new Manager("4", "经理111", "山东高密2", 65));
	}
	
	private String _name = "sss";
	
	public String name{
		&{
			return this._name;
		}
		+{
			if(this._name === value){
				return;
			}
			this._name = value;
			notifyChanged("name");
		}
	}
	
	private boolean _flag = true;
	public boolean flag{
		&{
			return this._flag;
		}
		+{
			if(this._flag === value){
				return;
			}
			this._flag = value;
			notifyChanged("flag");
		}
	}
	
	private int _age = 70;
	public int age{
		&{
			return this._age;
		}
		+{
			if(this._age === value){
				return;
			}
			this._age = value;
			notifyChanged("age");
		}
	}
	
	private int _width = 18;
	public int width{
		&{
			return this._width;
		}
		+{
			if(this._width === value){
				return;
			}
			this._width = value;
			notifyChanged("width");
		}
	}
	
	private int _height = 18;
	public int height{
		&{
			return this._height;
		}
		+{
			if(this._height === value){
				return;
			}
			this._height = value;
			notifyChanged("height");
		}
	}
	
	EventHandler h = (Event e)->{
		alert("Hello world");
	};
	
	@Override
	public String toString() {
		return this._name + "2" + "; age : " + this._age;
	}
	
	public ConverterFunction to=(Object data) ->{
		return data + "px";
	};
	
	public ConverterFunction from=(Object data) ->{
		return data;
	};
	
	private Collection<Person> _persons = new ObservableCollection<>();
	public Collection<Person> persons{
		&{
			return this._persons;
		}
		+{
			this._persons = value; 
		}
	}
	 
	public MouseEventHandler addChild = (MouseEvent event)->{
		persons.add(new Manager("child1", "新增张三", "山东高密新增", 35));
	};
	 
	public MouseEventHandler deleteChild =  (MouseEvent event)->{
		List<Person> toBeDeleted = new ArrayList<Person>();
		for(Person p : persons){
			if(p.selected){
				toBeDeleted.add(p);
			} 
		}
		
		if(toBeDeleted.size>0){
			persons.removeAll(toBeDeleted);
		}
	};
	
	public MouseEventHandler nextPage =  (MouseEvent event)->{
		ObservableCollection<Person> nextPage = new ObservableCollection<Person>();
		nextPage.add(new Person("11" + Math.random(), "张三1" + Math.random(), "山东高密", 65));
		nextPage.add(new Person("21" + Math.random(), "张三11" + Math.random(), "山东高密1", 65));
		nextPage.add(new Person("31" + Math.random(), "张三21" + Math.random(), "山东高密2", 65));
		nextPage.add(new Person("41" + Math.random(), "张三31" + Math.random(), "山东高密2", 65)); 
		
		if(persons != null){ 
			persons.clear(); 
		}
		persons.addAll(nextPage); 
	};
	
	native void  ggg() /*-{
	
	}-*/;
} 

//class FirstTemplateSelector extends TemplateSelector{
//
//	@Override
//	protected Template doSelect(Object data) {
//		if(data instanceof Manager){
//			return new ManagerTableRow();
//		}  else if(data instanceof Person){
//			return new TableRow();
//		}
//		return null;
//	}
//	
//}

