sentence: frag | ipmat
frag: np
np: NPR | ipemb N | nml N | pp N | N | D N | ipemb PRO
NPR: "トロッコ" | "芥川龍之介" | "良平（りょうへい）" | "熱海（あたみ）" | "小田原" | "良平"
ipmat: pp PU npprd AX AXD PU | pp nptmp pp PU ppprp VB AXD PU | ppprp VB AXD FN AX VB2 PU | pp pp npnsbjn PU pp VB FN P VB PU
pp: np P | P | np P P
npprd: pp iprel N | numclp
iprel: npprd AX
ipemb: pp PU pp VB AXD | PU pp PU advp pp VB VB0 PU | pp VB AX
numclp: NUM CL | NUM
nml: conjp np
conjp: np
PU: "、" | "。" | "――"
AX: "だっ" | "の" | "で" | "だ"
AXD: "た"
P: "は" | "の" | "に" | "が" | "へ" | "を" | "といったところが" | "で"
N: "年" | "の" | "間" | "工事" | "軽便鉄道敷設（ふせつ）" | "村外（はず）れ" | "面白さ" | "トロッコ" | "上" | "土工" | "後（うしろ）" | "土"
VB: "始まっ" | "行っ" | "見物" | "見" | "運搬" | "佇（たたず）" | "いる" | "積ん"
NUM: "八" | "二人"
CL: "つ"
nptmp: QN
ppprp: ipnml P
ipnml: pp VB | pp pp VB
QN: "毎日"
D: "その"
advp: ADV
FN: "の" | "ん"
VB2: "ある"
PRO: "それ"
VB0: "する"
ADV: "唯（ただ）"
npnsbjn: numclp
%import common.WS
%ignore WS
