package dd;

import org.w3c.html.*;

public class Test3 {

<html >
<head>
</head>
 
<body>
 
 
<div className="w" >
	<div id="service-2013">
		<dl className="fore1">
			<dt><b></b><strong>购物指南</strong></dt>
			<dd>
				<div><a href="http://help.jd.com/help/question-56.html" target="_blank" rel="nofollow">购物流程</a></div>
				<div><a href="http://help.jd.com/help/question-57.html" target="_blank" rel="nofollow">会员介绍</a></div>
				<div><a href="http://help.jd.com/help/question-181.html" target="_blank" rel="nofollow">团购/机票</a></div>
				<div><a href="http://help.jd.com/help/question-61.html" target="_blank" rel="nofollow">常见问题</a></div>
				<div><a href="http://help.jd.com/help/question-63.html" target="_blank" rel="nofollow">大家电</a></div>
				<div><a href="http://help.jd.com/index.html" target="_blank" rel="nofollow">联系客服</a></div>
			</dd>
		</dl>
		<dl className="fore2">		
			<dt><b></b><strong>配送方式</strong></dt>
			<dd>
				<div><a href="http://help.jd.com/help/question-64.html" target="_blank" rel="nofollow">上门自提</a></div>
				<div><a href="http://help.jd.com/help/question-360.html" target="_blank" rel="nofollow">211限时达</a></div>
				<div><a href="http://help.jd.com/help/distribution-768.html" target="_blank" rel="nofollow">配送服务查询</a></div>
				<div><a href="http://help.jd.com/help/question-892.html#help2215" target="_blank" rel="nofollow">配送费收取标准</a></div>
				<div><a href="http://market.jd.com/giftcard/index.html#one5" target="_blank" rel="nofollow">如何送礼</a></div>
				<div><a href="http://en.jd.com/chinese.html" target="_blank">海外配送</a></div>
			</dd>
		</dl>
		<dl className="fore3">
			<dt><b></b><strong>支付方式</strong></dt>
			<dd>
				<div><a href="http://help.jd.com/help/question-67.html" target="_blank" rel="nofollow">货到付款</a></div>
				<div><a href="http://help.jd.com/help/question-68.html" target="_blank" rel="nofollow">在线支付</a></div>
				<div><a href="http://help.jd.com/help/question-71.html" target="_blank" rel="nofollow">分期付款</a></div>
				<div><a href="http://help.jd.com/help/question-69.html" target="_blank" rel="nofollow">邮局汇款</a></div>
				<div><a href="http://help.jd.com/help/question-70.html" target="_blank" rel="nofollow">公司转账</a></div>
			</dd>
		</dl>
		<dl className="fore4">		
			<dt><b></b><strong>售后服务</strong></dt>
			<dd>
				<div><a href="http://myjd.jd.com/afs/help/afshelp.action" target="_blank" rel="nofollow">售后政策</a></div>
				<div><a href="http://help.jd.com/help/question-99.html" target="_blank" rel="nofollow">价格保护</a></div>
				<div><a href="http://help.jd.com/help/question-100.html" target="_blank" rel="nofollow">退款说明</a></div>
				<div><a href="http://myjd.jd.com/repair/repairs.action" target="_blank" rel="nofollow">返修/退换货</a></div>
				<div><a href="http://help.jd.com/help/question-881.html" target="_blank" rel="nofollow">取消订单</a></div>
			</dd>
		</dl>
		<dl className="fore5">
			<dt><b></b><strong>特色服务</strong></dt>
			<dd>		
				<div><a href="http://help.jd.com/help/question-79.html" target="_blank">夺宝岛</a></div>
				<div><a href="http://help.jd.com/help/question-86.html" target="_blank">DIY装机</a></div>
				<div><a href="http://fuwu.jd.com/" target="_blank" rel="nofollow">延保服务</a></div>
				<div><a href="http://giftcard.jd.com/market/index.action" target="_blank" rel="nofollow">京东E卡</a></div>
				<div><a href="http://help.jd.com/help/question-91.html" target="_blank" rel="nofollow">节能补贴</a></div>
				<div><a href="http://mobile.jd.com/" target="_blank" rel="nofollow">京东通信</a></div>
			</dd>
		</dl>
		<div className="fr"><div className="sm" id="branch-office">
	<div className="smt">
		<h3>京东自营覆盖区县</h3>
	</div>
	<div className="smc">
		<p>京东已向全国1955个区县提供自营配送服务，支持货到付款、POS机刷卡和售后上门服务。</p>
		<p className="ar"><a href="http://help.jd.com/help/distribution-768.html" target="_blank">查看详情&nbsp;></a></p>
	</div>
</div>
		<span className="clr"></span>
	</div>
</div><!-- service end --><!-- service home end -->
 
 
<div className="w" >
	<div id="footer-2013">
		<div className="links">
		<a href="http://www.jd.com/intro/about.aspx" target="_blank" rel="nofollow">关于我们</a>|
		<a href="http://www.jd.com/contact/" target="_blank" rel="nofollow">联系我们</a>|<a href="http://zhaopin.jd.com/" target="_blank" rel="nofollow">人才招聘</a>
		|
		<a href="http://www.jd.com/contact/joinin.aspx" target="_blank" rel="nofollow">商家入驻</a>
		|
		<a href="http://jzt.jd.com" target="_blank" rel="nofollow">营销中心</a>
		|<a href="http://app.jd.com/" target="_blank" rel="nofollow">手机京东</a>
		|
		<a href="http://club.jd.com/links.aspx" target="_blank">友情链接</a>
		|<a href="http://media.jd.com/" target="_blank">销售联盟</a>
		|<a target="_blank" href="http://club.jd.com/">京东社区</a>
		|<a target="_blank" href="http://gongyi.jd.com">京东公益</a>
		|<a target="_blank" href="http://en.jd.com/">English Site</a>
		|<a target="_blank" href="http://help.en.jd.com/help/question-46.html">Contact Us</a></div>
		<div className="copyright">北京市公安局朝阳分局备案编号110105014669&nbsp;&nbsp;|&nbsp;&nbsp;京ICP证070359号&nbsp;&nbsp;|&nbsp;&nbsp;互联网药品信息服务资格证编号(京)-非经营性-2011-0034&nbsp;&nbsp;|&nbsp;&nbsp;新出发京零&nbsp;字第大120007号<br/>
		<a target="_blank" href="http://misc.360buyimg.com/skin/df/i/com/f_music.jpg" rel="nofollow">音像制品经营许可证苏宿批005号</a>&nbsp;&nbsp;|&nbsp;&nbsp;出版物经营许可证编号新出发(苏)批字第N-012号&nbsp;&nbsp;|&nbsp;&nbsp;互联网出版许可证编号新出网证(京)字150号<br/>
		<a target="_blank" href="http://misc.360buyimg.com/wz/wlwhjyxkz.jpg">网络文化经营许可证京网文[2011]0168-061号</a>&nbsp;&nbsp;Copyright&nbsp;&copy;&nbsp;2004-2014&nbsp;&nbsp;京东JD.com&nbsp;版权所有<br />京东旗下网站：
		<a href="http://www.360top.com/" target="_blank">360TOP</a>&nbsp;&nbsp;<a target="_blank" href="http://www.paipai.com/">拍拍网</a>&nbsp;&nbsp;
		<a target="_blank" href="https://www.wangyin.com/">网银在线</a></div>
		<div className="authentication"><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202007080200026" target="_blank" rel="nofollow">
		<img  width="108" height="40" alt="经营性网站备案中心"/></a>
		<script type="text/JavaScript">
		function CNNIC_change(eleId){var str= document.getElementById(eleId).href;var str1 =str.substring(0,(str.length-6));str1+=CNNIC_RndNum(6); document.getElementById(eleId).href=str1;}function CNNIC_RndNum(k){var rnd=""; for (var i=0;i &lt; k;i++) rnd+=Math.floor(Math.random()*10); return rnd;}
		</script>
		<a href="https://ss.cnnic.cn/verifyseal.dll?sn=2008070300100000031&ct=df&pa=294005" tabIndex="-1" id="urlknet" target="_blank" rel="nofollow"> 
		<img alt="&#x53EF;&#x4FE1;&#x7F51;&#x7AD9;"  width="108" height="40" oncontextmenu="return false;" onclick="CNNIC_change('urlknet')" /></a>
		<a href="http://www.bj.cyberpolice.cn/index.do" target="_blank" rel="nofollow">
		<img  width="108" height="40" alt="朝阳网络警察"/></a>
		<a href="https://search.szfw.org/cert/l/CX20120111001803001836" target="_blank" rel="nofollow">
		<img  width="112" height="40"/></a></div>
	</div>
</div><!-- footer end -->
 
<!-- footer end -->
</div>
 
</body>
</html>

	public Test3() {
		// TODO Auto-generated constructor stub
	}

	public Test3(Object value) {
		super(value);
		// TODO Auto-generated constructor stub
	}

}
