# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Test::Unit::TestCase; end
module ::Test::Unit::TestCase; end
module ::Test::Unit::TestCase; end
