# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActionMailer::Base::Mail::Message; end
module ActiveSupport::ActionController::Base; end
module Rails::Generators::NamedBase; end
module Setler::ActiveRecord::Base; end
