# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Chalk::Tools::RedactionUtils; end
module Chalk::Tools::RedactionUtils::RedactionDirectiveSpec; end
module Opus::Enum; end
module Opus::Enum; end
module Opus::Ownership; end
module Opus::Sensitivity::Utils; end
