s/^,//g
1,/MUNICIPIO/ d
s/Servicio P.*$//g
s/^,*.?*$//g
/^$/ d
s/\.//g
s/,,/,/g
#"MUNICIPIOS","TOTAL","HOMBRES_MENOS_25","HOMBRES_25_44","HOMBRES_MAS_45","MUJERES_MENOS_25","MUJERES_25_44","MUJERES_MAS_45","AGRICULTURA","INDUSTRIA","CONSTRUCCION","SERVICIOS","SIN_EMPLEO_ANTERIOR"

