# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   tapioca generate

# typed: true

module Turbolinks
end

module Turbolinks::Source
  def self.asset_path; end
end

Turbolinks::Source::VERSION = T.let(T.unsafe(nil), String)

Turbolinks::VERSION = T.let(T.unsafe(nil), String)
