package collection;

import org.w3c.dom.Node;

public class XAxis extends Template{
	<%
		<Iterator begin=30 end = 300 step = 50 xmlns:svg = "http://www.w3.org/2000/svg">
			<svg:text x={Binding property="count" context="status" converteTo="converteX"} y=200>2001</text>
		</Iterator>
	%>
	protected XAxis(Node parent) { 
		super(parent);
	}
	
	public ConverterFunction converteX = (Object data)->{
		return 30+(int)data*50;
	};
}