'\" te
.\" Copyright (c) 2002, Sun Microsystems, Inc. All Rights Reserved 
.TH ssh-socks5-proxy-connect 1 "2002 年 10 月 30 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
ssh-socks5-proxy-connect \- SOCKS5 用の Secure Shell プロキシ
.SH 形式
.LP
.nf
\fB/usr/lib/ssh/ssh-socks5-proxy-connect\fR 
     [\fB-h\fR \fIsocks5_proxy_host\fR] 
     [\fB-p\fR \fIsocks5_proxy_port\fR] \fIconnect_host\fR \fIconnect_port\fR
.fi

.SH 機能説明
.sp
.LP
SOCKS5 (RFC 1928) を使用する、\fBssh\fR(1) 用のプロキシコマンド。通常は、ネットワークの外部の接続が SOCKS ゲートウェイサーバー経由でのみ許可される場合に使用されます。
.sp
.LP
このプロキシコマンドは、RFC 1928 で定義されたどの SOCKS5 認証メカニズムも提供しません。匿名接続だけが可能です。
.SH オプション
.sp
.LP
サポートしているオプションは、次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fB-h\fR \fIsocks5_proxy_host\fR\fR
.ad
.RS 24n
.rt  
接続に使用するプロキシ Web サーバーを指定します。\fBSOCKS5_SERVER\fR 環境変数をオーバーライドします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR \fIsocks5_proxy_port\fR\fR
.ad
.RS 24n
.rt  
プロキシ Web サーバーが実行されるポートを指定します。指定されていない場合は、ポート 80 が使用されます。\fBSOCKS5_PORT\fR 環境変数をオーバーライドします。
.RE

.SH オペランド
.sp
.LP
次のオペランドがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fIsocks5_proxy_host\fR\fR
.ad
.RS 21n
.rt  
プロキシのホスト名または IP アドレス (IPv4 または IPv6)。
.RE

.sp
.ne 2
.mk
.na
\fB\fIsocks5_proxy_port\fR\fR
.ad
.RS 21n
.rt  
\fIsocks5_proxy_host\fR 上の接続先の数値のポート番号。
.RE

.sp
.ne 2
.mk
.na
\fB\fIconnect_host\fR\fR
.ad
.RS 21n
.rt  
SOCKS ゲートウェイで接続する先のリモートホストの名前。
.RE

.sp
.ne 2
.mk
.na
\fB\fIconnect_port\fR\fR
.ad
.RS 21n
.rt  
\fIconnect_host\fR 上の、SOCKS ゲートウェイで接続する先の数値のポート番号。
.RE

.SH 使用例
.sp
.LP
プロキシ接続コマンドを使用するには、\fBssh_config\fR(4) で \fBProxyCommand\fR を構成することをお勧めします (例 1 および例 2 を参照)。例 3 は、\fBssh\fR(1) を実行しているときに、プロキシコマンドをコマンド行でどのように指定できるかを示しています。
.LP
\fB例 1 \fR環境からのプロキシの設定
.sp
.LP
次の例では、環境からプロキシが設定されるときに \fBssh_config\fR(4) で \fBssh-socks5-proxy-connect\fR を使用します。

.sp
.in +2
.nf
\fBHost playtime.foo.com
    ProxyCommand /usr/lib/ssh/ssh-socks5-proxy-connect \e
        playtime.foo.com 22\fR
.fi
.in -2
.sp

.LP
\fB例 2 \fRプロキシ環境変数のオーバーライド
.sp
.LP
次の例では、\fBssh_config\fR(4) で \fBssh-socks5-proxy-connect\fR を使用して、プロキシ環境変数をオーバーライド (設定されていない場合は設定) します。

.sp
.in +2
.nf
\fBHost playtime.foo.com
    ProxyCommand /usr/lib/ssh/ssh-socks5-proxy-connect -h socks-gw \e
        -p 1080 playtime.foo.com 22\fR
.fi
.in -2
.sp

.LP
\fB例 3 \fRコマンド行の使用
.sp
.LP
次の例では、\fBssh\fR(1) コマンド行から \fBssh-socks5-proxy-connect\fR を使用します。

.sp
.in +2
.nf
example$ \fBssh -o'ProxyCommand=/usr/lib/ssh/ssh-socks5-proxy-connect \e
    -h socks-gw -p 1080 playtime.foo.com 22' playtime.foo.com\fR
.fi
.in -2
.sp

.SH 環境
.sp
.ne 2
.mk
.na
\fB\fBSOCKS5_SERVER\fR\fR
.ad
.RS 17n
.rt  
デフォルトのプロキシホストを指定するために、\fIsocks5_proxy_host\fR オペランドを取得します。
.RE

.sp
.ne 2
.mk
.na
\fB\fBSOCKS5_PORT\fR\fR
.ad
.RS 17n
.rt  
デフォルトのプロキシポートを指定するために、\fIsocks5_proxy_port\fR オペランドを取得します。
.RE

.SH 終了ステータス
.sp
.LP
次の終了ステータスが返されます。
.sp
.ne 2
.mk
.na
\fB\fB0\fR \fR
.ad
.RS 6n
.rt  
正常終了。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 6n
.rt  
エラーが発生した。
.RE

.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件network/ssh
_
インタフェースの安定性確実
.TE

.SH 関連項目
.sp
.LP
\fBssh\fR(1), \fBssh-http-proxy-connect\fR(1), \fBssh_config\fR(4), \fBattributes\fR(5) 
