'\" te
.\"  Copyright (c) 1994 Sun Microsystems, Inc. All Rights Reserved.
.TH uptime 1 "1994 年 3 月 18 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
uptime \- システムの稼働時間の表示
.SH 形式
.LP
.nf
\fBuptime\fR 
.fi

.SH 機能説明
.sp
.LP
\fBuptime\fR コマンドは、現在の時間、システムが稼働している時間、過去 1、5、および 15 分間の実行待ち行列内の平均ジョブ数を出力します。これは、基本的に、\fBw\fR(1) コマンドの先頭行です。
.SH 使用例
.sp
.LP
次に、\fBuptime\fR が提供する出力例を示します。
.sp
.in +2
.nf
example% uptime
10:47am  up 27 day(s), 50 mins,  1 user,  load average: 0.18, 0.26, 0.20
.fi
.in -2
.sp

.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fB属性タイプ\fR\fB属性値\fR
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBw\fR(1)、\fBwho\fR(1)、\fBwhodo\fR(1M)、\fBattributes\fR(5)
.SH 注意事項
.sp
.LP
\fBwho\fR \fB-b\fR は、システムが前回ブートした時間を示します。
