.Dd August 2, 2015
.Dt GCL-CLONE 8
.Os Swarm-GDP
.Sh NAME
.Nm gcl-clone
.Nd create clone of existing GDP log
.Sh SYNOPSIS
.Nm gcl-clone
.Op Fl D Ar debug-spec
.Op Fl G Ar router-ip
.Ar gcl-name
.Ar logd-name ...
.Sh DESCRIPTION
.Nm
creates a clone of a given existing GDP log
.Ar gcl-name
onto one or more log daemons specified as
.Ar logd-name .
The metadata is copied from
.Ar gcl-name .
The data itself is not copied.
.Pp
.Nm
exists for the sole purpose of testing replication.
.Ss "Warning"
This implementation will change or go away entirely in the future,
and the command will probably be subsumed into a swarm service.
.Sh OPTIONS
.Bl -tag
.It Fl D Ar debug-spec
Turns on debugging flags using the libep-style format.
Useful only with the code in hand.
.It Fl G Ar router-ip
Contact the given IP address (which may be a DNS name)
to get a connection to the GDP routing layer.
This will be replaced by automatic discovery
(for example, using Zeroconf)
soon.
The address may have an optional port number after a colon.
If this is not specified,
the names listed in the
.Va swarm.gdp.routers
runtime administrative parameter
are searched.
.El
.Sh EXIT STATUS
.Bl -tag
.It Li EX_CANTCREAT
The log already exists.
.It Li EX_NOINPUT
The source log name could not be opened
or the metadata was not available.
.It Li EX_USAGE
Command line parameters are incorrect.
.It Li EX_CANTCREAT
One or more of the clones could not be created.
.El
.\".Sh ADMINISTRATIVE PARAMETERS
.\".Sh ENVIRONMENT
.\".Sh FILES
.Sh SEE ALSO
.Xr gdp 7 ,
.Xr gdplogd 8
.\".Sh EXAMPLES
.\".Sh BUGS
